import type { Question } from './types'

/**
 * LES 55 QUESTIONS PROBABLES D'ENTRAÎNEMENT.
 * Source : `14_Nouvelles_questions_probables.md`. Couvrent tous les thèmes du cours.
 * Format : réponse-clé + notions à citer + comment construire + mémo.
 */
export const questionsProbables: Question[] = [
  // A. Diagnostic stratégique global (1-6)
  {
    id: 'qp-1', origine: 'probable', numero: 1, categorie: 'fondements', priorite: 1,
    enonce: "Qu'est-ce qu'une « bonne » stratégie ?",
    reponse: "Un diagnostic lucide + un choix cohérent + des actions alignées créant un avantage concurrentiel durable.",
    notions: ['bonne-strategie', 'strategie', 'avantage-concurrentiel-durable', 'plan-action'],
    commentConstruire: 'Définition → critères de cohérence → exemple.',
    memo: 'Diagnostic → choix → cohérence.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-2', origine: 'probable', numero: 2, categorie: 'fondements', priorite: 2,
    enonce: "Différence entre objectif et stratégie ?",
    reponse: "L'objectif est le but (où aller), la stratégie est le chemin cohérent (comment, avec quelles ressources).",
    notions: ['buts-objectifs', 'strategie', 'business-model'],
    sources: ['questions-probables'],
  },
  {
    id: 'qp-3', origine: 'probable', numero: 3, categorie: 'fondements', priorite: 1,
    enonce: "Qu'est-ce qu'un avantage concurrentiel durable ?",
    reponse: "Un avantage difficile à imiter et à transférer, souvent fondé sur des ressources immatérielles.",
    notions: ['avantage-concurrentiel-durable', 'ressources-intangibles', 'transferabilite'],
    memo: 'Ex. la marque Oncle Hansi.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-4', origine: 'probable', numero: 4, categorie: 'diagnostic', priorite: 1,
    enonce: "Expliquez la matrice parties prenantes intérêt × pouvoir.",
    reponse: "4 cases → 4 stratégies : gérer de près (engager avec attention) / satisfaire / informer / veiller.",
    notions: ['matrice-pouvoir-interet', 'parties-prenantes'],
    commentConstruire: '2 axes → 4 quadrants → action pour chacun.',
    memo: 'Pouvoir × Intérêt.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-5', origine: 'probable', numero: 5, categorie: 'choix', priorite: 1,
    enonce: "Qu'apporte la grille SAF à une recommandation ?",
    reponse: "Elle filtre une option par Souhaitabilité (cohérence avec le diagnostic), Acceptabilité (parties prenantes, risque, retour), Faisabilité (ressources, compétences, contraintes légales).",
    notions: ['saf', 'souhaitabilite', 'acceptabilite', 'faisabilite'],
    memo: 'S-A-F.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-6', origine: 'probable', numero: 6, categorie: 'diagnostic', priorite: 1,
    enonce: "Comment passe-t-on d'un SWOT à une recommandation ?",
    reponse: "Croiser FF × OM (forces → saisir opportunités, faiblesses → parer menaces), puis filtrer par le SAF.",
    notions: ['swot', 'croisements-swot', 'saf'],
    piege: 'Rester descriptif sans croisement.',
    sources: ['questions-probables'],
  },

  // B. Diagnostic externe (7-12)
  {
    id: 'qp-7', origine: 'probable', numero: 7, categorie: 'diagnostic-externe', priorite: 1,
    enonce: "Citez et expliquez les 6 dimensions du PESTEL (version du cours).",
    reponse: "P, E, S, T, É écologique/éthique fusionné, L.",
    notions: ['pestel', 'facteur-politique', 'facteur-economique', 'facteur-socioculturel', 'facteur-technologique', 'facteur-environnemental-ethique', 'facteur-legal'],
    commentConstruire: '1 ligne par dimension + 1 facteur concret.',
    memo: 'Le E fusionné est la signature du cours.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-8', origine: 'probable', numero: 8, categorie: 'diagnostic-externe', priorite: 1,
    enonce: "Quelle est la 6ᵉ force de Porter ajoutée dans le cours ?",
    reponse: "L'État (pouvoirs publics et réglementation).",
    notions: ['etat-sixieme-force', 'porter-five-forces'],
    memo: '5 forces + État.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-9', origine: 'probable', numero: 9, categorie: 'diagnostic', priorite: 1,
    enonce: "Différence entre opportunité et force ?",
    reponse: "Opportunité = externe (PESTEL, Porter) ; force = interne (ressources).",
    notions: ['opportunite', 'force', 'diagnostic-externe', 'diagnostic-interne'],
    piege: "Piège classique d'examen — le plus dangereux du cours.",
    sources: ['questions-probables'],
  },
  {
    id: 'qp-10', origine: 'probable', numero: 10, categorie: 'diagnostic-externe', priorite: 1,
    enonce: "Comment relier PESTEL et Porter ?",
    reponse: "Le PESTEL (macro) explique l'évolution des 5 forces (micro) : une loi augmente les barrières à l'entrée, une taxe rend un substitut compétitif.",
    notions: ['pestel', 'porter-five-forces', 'strates-environnement', 'barriere-entree'],
    memo: 'Macro éclaire micro.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-11', origine: 'probable', numero: 11, categorie: 'diagnostic-externe', priorite: 2,
    enonce: "Analysez la rivalité dans un secteur saturé (ex. eau embouteillée).",
    reponse: "Rivalité forte + substituts forts → océan rouge (corrigé TP02B : rivalité 4, substituts 4).",
    notions: ['rivalite-concurrents', 'menace-substituts', 'ocean-rouge', 'toile-porter'],
    commentConstruire: 'Noter chaque force /5 avec justification factuelle → conclure océan rouge ou bleu.',
    sources: ['questions-probables', 'corrige-tp02b'],
  },
  {
    id: 'qp-12', origine: 'probable', numero: 12, categorie: 'diagnostic-externe', priorite: 2,
    enonce: "Qu'est-ce qu'une stratégie océan bleu ?",
    reponse: "Créer un espace non disputé, via la matrice ERAC.",
    notions: ['ocean-bleu', 'erac', 'innovation-valeur'],
    memo: 'Ex. Cirque du Soleil. E-R-A-C.',
    sources: ['questions-probables'],
  },

  // C. Diagnostic interne (13-17)
  {
    id: 'qp-13', origine: 'probable', numero: 13, categorie: 'diagnostic-interne', priorite: 1,
    enonce: "Distinguez ressources matérielles et immatérielles.",
    reponse: "3 matérielles (financières, physiques, humaines) / 3 immatérielles (organisation, technologie, réputation).",
    notions: ['ressources-tangibles', 'ressources-intangibles', 'ressources'],
    memo: 'Immatériel = peu imitable = durable.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-14', origine: 'probable', numero: 14, categorie: 'diagnostic-interne', priorite: 1,
    enonce: "Pourquoi les ressources immatérielles fondent-elles un avantage durable ?",
    reponse: "Peu transférables → peu imitables → durables.",
    notions: ['transferabilite', 'ressources-intangibles', 'avantage-concurrentiel-durable'],
    sources: ['questions-probables'],
  },
  {
    id: 'qp-15', origine: 'probable', numero: 15, categorie: 'diagnostic-interne', priorite: 1,
    enonce: "Décrivez la chaîne de valeur de Porter.",
    reponse: "5 activités principales + 4 de soutien → marge.",
    notions: ['chaine-de-valeur', 'activites-principales', 'activites-soutien', 'marge'],
    memo: 'Amont-production-aval-marketing-services + infra/RH/techno/achats.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-16', origine: 'probable', numero: 16, categorie: 'diagnostic-interne', priorite: 1,
    enonce: "Où agir dans la chaîne de valeur pour réduire l'empreinte carbone ?",
    reponse: "Maillon par maillon, activités principales puis de soutien.",
    notions: ['chaine-valeur-durable', 'chaine-de-valeur', 'achats-it-responsables'],
    memo: 'Décarboner = remonter la chaîne.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-17', origine: 'probable', numero: 17, categorie: 'diagnostic-interne', priorite: 2,
    enonce: "Qu'est-ce que la coopétition ?",
    reponse: "Coopérer avec des concurrents au sein du système de valeur → externalités positives.",
    notions: ['coopetition', 'systeme-de-valeur', 'externalite-positive'],
    memo: 'Lien durabilité : partage d’infrastructures vertes.',
    sources: ['questions-probables'],
  },

  // D. Business model & BMC (18-23)
  {
    id: 'qp-18', origine: 'probable', numero: 18, categorie: 'business-model', priorite: 1,
    enonce: "Expliquez le modèle RCOV.",
    reponse: "Ressources + Compétences/Organisation → proposition de Valeur → Profit, avec une boucle de retour de l'organisation vers les ressources.",
    notions: ['rcov', 'ressources', 'competences', 'proposition-de-valeur', 'equation-de-profit'],
    memo: 'R-C-O-V.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-19', origine: 'probable', numero: 19, categorie: 'business-model', priorite: 2,
    enonce: "Quelles sont les 4 dimensions de la valeur ?",
    reponse: "Création / délivrance / captation / répartition de la valeur.",
    notions: ['business-model', 'proposition-de-valeur', 'architecture-de-valeur', 'equation-de-profit'],
    piege: "Le cours emploie « production et délivrance » et « crée et répartit » ; « capture » est un complément terminologique standard.",
    sources: ['questions-probables'],
  },
  {
    id: 'qp-20', origine: 'probable', numero: 20, categorie: 'business-model', priorite: 1,
    enonce: "Citez les 9 blocs du BMC.",
    reponse: "Segments, proposition de valeur, canaux, relations clients, flux de revenus, ressources clés, activités clés, partenaires clés, structure de coûts.",
    notions: ['bmc', 'segments-clients', 'proposition-de-valeur', 'canaux', 'relations-clients', 'flux-revenus', 'ressources-cles', 'activites-cles', 'partenaires-cles', 'structure-couts'],
    memo: 'Proposition de valeur au centre.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-21', origine: 'probable', numero: 21, categorie: 'business-model', priorite: 1,
    enonce: "Quelles sont les limites du BMC ?",
    reponse: "Statique, centré interne, néglige la concurrence, pensé start-up et mono-activité.",
    notions: ['bmc', 'porter-five-forces'],
    piege: 'On les oublie souvent — alors que le cours les donne AVANT le contenu.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-22', origine: 'probable', numero: 22, categorie: 'business-model', priorite: 1,
    enonce: "Qu'est-ce que l'équation de profit ?",
    reponse: "Revenus (fixes/variables) − structure de coûts.",
    notions: ['equation-de-profit', 'flux-revenus', 'structure-couts'],
    memo: 'Ex. Oncle Hansi : cotisations + redevances − coûts légers.',
    sources: ['questions-probables', 'corrige-hansi'],
  },
  {
    id: 'qp-23', origine: 'probable', numero: 23, categorie: 'business-model', priorite: 2,
    enonce: "Analysez un mini-cas avec le BMC.",
    reponse: "Remplir les 9 blocs → identifier la ressource clé → vérifier la cohérence proposition / segment / revenus.",
    notions: ['bmc', 'ressources-cles', 'proposition-de-valeur', 'segments-clients'],
    commentConstruire: 'Pour chaque phrase du cas, demander à quel bloc elle répond.',
    sources: ['questions-probables'],
  },

  // E. Business model durable (24-28)
  {
    id: 'qp-24', origine: 'probable', numero: 24, categorie: 'business-model-durable', priorite: 1,
    enonce: "Qu'ajoute le Sustainable BMC au BMC classique ?",
    reponse: "Mission / raison d'être (bloc 0) + Impacts positifs (10) + Externalités négatives (11).",
    notions: ['bmc-durable', 'mission', 'impacts-positifs', 'externalite-negative'],
    memo: 'BMC + Mission + Impacts ±.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-25', origine: 'probable', numero: 25, categorie: 'business-model-durable', priorite: 1,
    enonce: "Où se cachent les externalités négatives dans un BM ?",
    reponse: "Souvent dans la structure de coûts : coûts sociaux et environnementaux non comptabilisés. On les repère aussi dans les ressources clés (matériaux) et les activités clés (procédés).",
    notions: ['externalite-negative', 'structure-couts', 'ressources-cles', 'activites-cles'],
    piege: 'Piège-clé : on cherche ce qui MANQUE au tableau.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-26', origine: 'probable', numero: 26, categorie: 'business-model-durable', priorite: 2,
    enonce: "Donnez des exemples de revenus durables.",
    reponse: "Leasing, réemploi, services, économie circulaire — plutôt que la vente de biens neufs.",
    notions: ['economie-fonctionnalite', 'flux-revenus', 'economie-circulaire', 'metamorphose-bmc'],
    sources: ['questions-probables'],
  },
  {
    id: 'qp-27', origine: 'probable', numero: 27, categorie: 'business-model-durable', priorite: 1,
    enonce: "Comment intégrer la durabilité sans tuer la viabilité économique ?",
    reponse: "Internaliser progressivement, viser la réputation et le risque évité, ouvrir de nouveaux revenus circulaires. Montrer la tension CT/LT.",
    notions: ['bmc-durable', 'tensions-strategiques', 'metamorphose-bmc', 'economie-fonctionnalite'],
    sources: ['questions-probables'],
  },
  {
    id: 'qp-28', origine: 'probable', numero: 28, categorie: 'business-model-durable', priorite: 1,
    enonce: "Qu'est-ce que la « métamorphose » du BMC ?",
    reponse: "Chaque bloc traditionnel est réécrit en version durable : ressources → renouvelables, canaux → responsables, revenus → usage et circularité, etc.",
    notions: ['metamorphose-bmc', 'bmc-durable'],
    sources: ['questions-probables', 'metamorphose-bmc'],
  },

  // F. Durabilité / ODD / limites / donut (29-35)
  {
    id: 'qp-29', origine: 'probable', numero: 29, categorie: 'durabilite', priorite: 1,
    enonce: "Qu'est-ce que l'Agenda 2030 ?",
    reponse: "Adopté le 25 septembre 2015 par 193 États : 17 ODD, 169 cibles, horizon 2030.",
    notions: ['agenda-2030', 'odd', 'cinq-p'],
    memo: '2015 / 193 / 17 / 169.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-30', origine: 'probable', numero: 30, categorie: 'durabilite', priorite: 1,
    enonce: "Citez les 5P.",
    reponse: "Populations, Planète, Prospérité, Paix, Partenariats.",
    notions: ['cinq-p', 'agenda-2030'],
    memo: '5P.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-31', origine: 'probable', numero: 31, categorie: 'durabilite', priorite: 1,
    enonce: "Durabilité forte vs faible ?",
    reponse: "Forte = capital naturel non substituable. Faible = substitution admise par le capital technique. Le cours défend la forte.",
    notions: ['durabilite-forte', 'durabilite-faible', 'capital-naturel'],
    sources: ['questions-probables'],
  },
  {
    id: 'qp-32', origine: 'probable', numero: 32, categorie: 'durabilite', priorite: 1,
    enonce: "Qu'est-ce que le « wedding cake » des ODD ?",
    reponse: "Hiérarchie biosphère > société > économie : l'économie est encastrée dans la société, elle-même dans la biosphère.",
    notions: ['wedding-cake', 'odd', 'durabilite-forte'],
    sources: ['questions-probables'],
  },
  {
    id: 'qp-33', origine: 'probable', numero: 33, categorie: 'durabilite', priorite: 1,
    enonce: "Combien de limites planétaires, et combien sont dépassées ?",
    reponse: "9 limites (Rockström, 2009), 7 sur 9 dépassées en 2025.",
    notions: ['limites-planetaires', 'plafond-ecologique'],
    memo: '9 limites, 7 franchies.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-34', origine: 'probable', numero: 34, categorie: 'durabilite', priorite: 1,
    enonce: "Expliquez le donut de Kate Raworth.",
    reponse: "Un espace juste entre un plancher social (12 fondements) et un plafond écologique (9 limites).",
    notions: ['donut', 'plancher-social', 'plafond-ecologique'],
    memo: 'Plancher social / plafond écologique.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-35', origine: 'probable', numero: 35, categorie: 'durabilite', priorite: 1,
    enonce: "Donnez les ordres de grandeur d'empreinte du cours.",
    reponse: "Monde ≈ 1,7 planète ; Suisse ≈ 3 planètes ; Overshoot Day ≈ 24 juillet 2025.",
    notions: ['empreinte-ecologique', 'jour-depassement', 'biocapacite'],
    sources: ['questions-probables'],
  },

  // G. Numérique & sobriété (36-41)
  {
    id: 'qp-36', origine: 'probable', numero: 36, categorie: 'numerique', priorite: 1,
    enonce: "Quels sont les 3 postes d'impact du numérique ?",
    reponse: "Terminaux + data centers + réseaux.",
    notions: ['trois-postes-numerique', 'data-center'],
    memo: 'T-D-R.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-37', origine: 'probable', numero: 37, categorie: 'numerique', priorite: 1,
    enonce: "Qu'est-ce que l'effet rebond ?",
    reponse: "Les gains d'efficacité sont réabsorbés par une hausse des usages. Quatre types : direct, indirect, de marché, de croissance.",
    notions: ['effet-rebond', 'sobriete-numerique', 'boucle-retroaction'],
    memo: 'Phrase-réflexe à placer partout.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-38', origine: 'probable', numero: 38, categorie: 'numerique', priorite: 1,
    enonce: "Définissez la sobriété numérique.",
    reponse: "« Mieux avec moins » : Questionner → Transférer → Améliorer ; sobriété + lucidité.",
    notions: ['sobriete-numerique', 'effet-rebond', 'besoins-fondamentaux'],
    memo: 'Q-T-A.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-39', origine: 'probable', numero: 39, categorie: 'numerique', priorite: 2,
    enonce: "Comment rendre la sobriété désirable ?",
    reponse: "La relier aux besoins réels (Max-Neef, Doyal & Gough, Nussbaum et les capabilités), au sens et au bien-être, pas à la privation. La sobriété substitue des satisfiers, elle ne réduit pas les besoins.",
    notions: ['besoins-fondamentaux', 'sobriete-numerique', 'sobriete-injuste'],
    sources: ['questions-probables', 'heuristique'],
  },
  {
    id: 'qp-40', origine: 'probable', numero: 40, categorie: 'numerique', priorite: 2,
    enonce: "Qu'est-ce que l'économie de l'attention ? Citez 2 mécanismes.",
    reponse: "Capter le temps de cerveau disponible : dark patterns, boucles dopaminergiques, bulles de filtres, « si c'est gratuit, c'est vous la matière première ».",
    notions: ['economie-attention', 'dark-patterns', 'technofeodalisme'],
    sources: ['questions-probables'],
  },
  {
    id: 'qp-41', origine: 'probable', numero: 41, categorie: 'numerique', priorite: 3,
    enonce: "Distinguez effet d'offre et effet d'usage.",
    reponse: "Offre = impact de produire et fournir la technologie ; usage = impact lié à son utilisation. À différencier des gains permis par cet usage.",
    notions: ['effet-offre-usage', 'effets-ocde', 'effet-rebond'],
    sources: ['questions-probables'],
  },

  // H. RNE / IA / données (42-48)
  {
    id: 'qp-42', origine: 'probable', numero: 42, categorie: 'rne', priorite: 1,
    enonce: "Quels sont les 4 axes de la RNE ?",
    reponse: "Économique, Technologique, Environnemental, Sociétal — ou, selon le Guide RNE : Données, Social, Environnement, Éthique et gouvernance.",
    notions: ['quatre-axes-rne', 'rne'],
    memo: 'É-T-E-S.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-43', origine: 'probable', numero: 43, categorie: 'rne', priorite: 1,
    enonce: "Privacy by design vs by default ?",
    reponse: "By design = protection dès la conception. By default = réglages par défaut les plus protecteurs.",
    notions: ['privacy-by-design', 'privacy-by-default'],
    piege: 'Ne pas confondre — piège classique.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-44', origine: 'probable', numero: 44, categorie: 'rne', priorite: 2,
    enonce: "Qu'est-ce que l'opt-in / double opt-in ?",
    reponse: "Consentement actif ; double = confirmation supplémentaire, par exemple un e-mail de validation.",
    notions: ['opt-in', 'privacy-by-default'],
    sources: ['questions-probables'],
  },
  {
    id: 'qp-45', origine: 'probable', numero: 45, categorie: 'rne', priorite: 1,
    enonce: "Quels niveaux de risque définit l'AI Act européen ?",
    reponse: "4 : inacceptable (interdit), élevé (conformité stricte), limité (transparence), minimal (libre). Entrée en application le 1ᵉʳ août 2024. Suisse : Convention du Conseil de l'Europe sur l'IA.",
    notions: ['ai-act', 'ia', 'position-suisse-ia'],
    sources: ['questions-probables'],
  },
  {
    id: 'qp-46', origine: 'probable', numero: 46, categorie: 'rne', priorite: 1,
    enonce: "Citez 3 principes de gestion responsable des données.",
    reponse: "But déterminé, transparence, minimisation — plus exactitude et compréhension.",
    notions: ['cinq-principes-collecte', 'minimisation-donnees', 'protection-donnees'],
    memo: 'But / transparence / minimisation.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-47', origine: 'probable', numero: 47, categorie: 'rne', priorite: 2,
    enonce: "Quels rôles de gouvernance numérique ?",
    reponse: "DPO, CDO, CISO, CAIO, Green/Sustainability Officer, Accessibility Officer. La charte numérique est collective (≠ stratégie).",
    notions: ['gouvernance-numerique-roles', 'charte-numerique'],
    sources: ['questions-probables'],
  },
  {
    id: 'qp-48', origine: 'probable', numero: 48, categorie: 'rne', priorite: 1,
    enonce: "En quoi la RNE est-elle un avantage stratégique ?",
    reponse: "Confiance, image, réduction des risques légaux et cyber, innovation, différenciation.",
    notions: ['rne', 'avantage-concurrentiel-durable', 'option-differenciation'],
    sources: ['questions-probables'],
  },

  // I. Accessibilité (49-52)
  {
    id: 'qp-49', origine: 'probable', numero: 49, categorie: 'accessibilite', priorite: 1,
    enonce: "Citez les 4 principes WCAG.",
    reponse: "Perceptible, Utilisable (Opérable), Compréhensible, Robuste.",
    notions: ['pour', 'wcag', 'accessibilite-numerique'],
    memo: 'POUR.',
    sources: ['questions-probables'],
  },
  {
    id: 'qp-50', origine: 'probable', numero: 50, categorie: 'accessibilite', priorite: 1,
    enonce: "Qu'est-ce que l'exclusion indirecte ?",
    reponse: "Un service légal et performant exclut de fait une population — par exemple les seniors chez SilverDigital, −12 % de clients de plus de 65 ans — sans intention discriminatoire.",
    notions: ['exclusion-indirecte', 'discrimination-directe', 'accessibilite-numerique'],
    sources: ['questions-probables', 'cas-silverdigital'],
  },
  {
    id: 'qp-51', origine: 'probable', numero: 51, categorie: 'accessibilite', priorite: 1,
    enonce: "« Le risque n'est pas juridique mais stratégique » : expliquez.",
    reponse: "Aucune loi n'est enfreinte, mais la perte de clientèle, de réputation et de marché constitue un risque stratégique majeur.",
    notions: ['exclusion-indirecte', 'double-levier-accessibilite', 'ressources-intangibles', 'tensions-strategiques'],
    memo: 'Phrase-clé du cas SilverDigital.',
    sources: ['questions-probables', 'cas-silverdigital'],
  },
  {
    id: 'qp-52', origine: 'probable', numero: 52, categorie: 'accessibilite', priorite: 2,
    enonce: "Citez 2 références légales d'accessibilité du cours.",
    reponse: "European Accessibility Act (juin 2025), eCH-0059, révision de la LHand, Art. 21A Cst-GE (intégrité numérique).",
    notions: ['european-accessibility-act', 'lhand', 'cadre-legal-accessibilite', 'integrite-numerique'],
    sources: ['questions-probables'],
  },

  // J. Achats IT / collecte de données (53-55)
  {
    id: 'qp-53', origine: 'probable', numero: 53, categorie: 'circularite', priorite: 1,
    enonce: "Expliquez les 3R et pourquoi l'ordre compte.",
    reponse: "Réduire > Réutiliser > Recycler : recycler est un dernier recours, coûteux en énergie et destructeur de la valeur ajoutée. Relève de l'ODD 12.",
    notions: ['trois-r', 'economie-circulaire', 'odd-12'],
    sources: ['questions-probables'],
  },
  {
    id: 'qp-54', origine: 'probable', numero: 54, categorie: 'circularite', priorite: 2,
    enonce: "Qu'est-ce que le coût du cycle de vie d'un achat IT ?",
    reponse: "Achat + fonctionnement + élimination — et non le prix d'achat seul. Critère central des achats responsables.",
    notions: ['cout-cycle-de-vie', 'achats-it-responsables', 'sept-principes-achats'],
    sources: ['questions-probables'],
  },
  {
    id: 'qp-55', origine: 'probable', numero: 55, categorie: 'pilotage', priorite: 2,
    enonce: "Quelle méthode pour comprendre un utilisateur avant de concevoir un service ?",
    reponse: "Observation / Interview / Sondage / Focus group, croisées par triangulation.",
    notions: ['collecte-donnees-utilisateurs', 'observation', 'interview', 'sondage', 'focus-group'],
    memo: 'O-I-S-F. Les gens ne font pas ce qu’ils disent.',
    sources: ['questions-probables', 'fiche-collecte'],
  },
]
