import type { Quiz } from './types'

/**
 * QUIZ — huit mécaniques, jamais uniquement du QCM.
 * Règle : toute option incorrecte porte une `explication` qui dit POURQUOI c'est faux,
 * et non « mauvaise réponse ». La validation du contenu le vérifie.
 */
export const quiz: Quiz[] = [
  // ---------------------------------------------------------------- QCM ----
  {
    id: 'qz-porter-couts', type: 'qcm', categorie: 'diagnostic-externe', priorite: 1,
    enonce: "Quelle force de Porter agit principalement — et uniquement — sur les coûts ?",
    notions: ['pouvoir-fournisseurs', 'profit-prix-couts'],
    options: [
      { id: 'a', texte: 'Le pouvoir de négociation des clients', correcte: false, explication: "Les clients agissent sur les DEUX leviers : ils font baisser les prix ET forcent à ajouter de la valeur, donc à augmenter les coûts." },
      { id: 'b', texte: 'Le pouvoir de négociation des fournisseurs', correcte: true },
      { id: 'c', texte: 'La menace des substituts', correcte: false, explication: "Les substituts forcent à limiter les prix pour maintenir le volume, et poussent à investir : prix ↓ ET coûts ↑." },
      { id: 'd', texte: 'La rivalité entre concurrents', correcte: false, explication: "La rivalité agit sur les deux leviers : guerre des prix d'un côté, dépenses de R&D et de marketing de l'autre." },
    ],
    correction: "Le tableau force → impact → raison du cours le montre : la ligne des fournisseurs est la seule à ne porter que « Coûts ↑ ». Logique : ton fournisseur te fait payer plus cher, il ne parle pas à tes clients.",
  },
  {
    id: 'qz-swot-nature', type: 'qcm', categorie: 'diagnostic', priorite: 1,
    enonce: "Le SWOT est avant tout…",
    notions: ['swot'],
    options: [
      { id: 'a', texte: "un outil de collecte d'information", correcte: false, explication: "Le SWOT n'a AUCUN contenu propre : il est entièrement rempli par les autres outils (PESTEL, Porter, diagnostic interne)." },
      { id: 'b', texte: 'un outil de synthèse et de confrontation', correcte: true },
      { id: 'c', texte: "un outil de mesure de l'attractivité d'un secteur", correcte: false, explication: "C'est la définition de Porter, pas du SWOT." },
      { id: 'd', texte: "un outil d'évaluation d'une option stratégique", correcte: false, explication: "C'est le rôle du SAF, qui intervient APRÈS le SWOT." },
    ],
    correction: "« Le SWOT = vision synthétique. » Il range ce que les autres outils ont produit, pour que le regard puisse faire des rapprochements et faire émerger des enjeux.",
  },
  {
    id: 'qz-saf-outil', type: 'qcm', categorie: 'choix', priorite: 1,
    enonce: "Quel outil le cours associe-t-il explicitement au critère de FAISABILITÉ ?",
    notions: ['faisabilite', 'saf', 'pestel'],
    options: [
      { id: 'a', texte: 'Le SWOT', correcte: false, explication: "Le SWOT est l'outil de la SOUHAITABILITÉ." },
      { id: 'b', texte: "L'analyse des parties prenantes", correcte: false, explication: "C'est l'outil de l'ACCEPTABILITÉ, avec l'analyse des risques." },
      { id: 'c', texte: 'Le PESTEL', correcte: true },
      { id: 'd', texte: 'La chaîne de valeur', correcte: false, explication: "Elle n'est associée à aucun critère du SAF dans le cours, même si la faisabilité mobilise en pratique le diagnostic interne." },
    ],
    correction: "Le cours associe Souhaitabilité → SWOT, Acceptabilité → parties prenantes + risques, Faisabilité → PESTEL. Tu peux ajouter que la faisabilité porte sur des contraintes « internes ET externes », donc mobilise aussi le diagnostic interne — mais cite d'abord l'association du cours.",
  },
  {
    id: 'qz-3r-repar', type: 'qcm', categorie: 'circularite', priorite: 1,
    enonce: "Dans quel R le cours classe-t-il la réparation d'un appareil ?",
    notions: ['trois-r'],
    options: [
      { id: 'a', texte: 'Réduire', correcte: true },
      { id: 'b', texte: 'Réutiliser', correcte: false, explication: "« Réutiliser » désigne l'usage d'un objet par des personnes AUTRES que les propriétaires initiaux (occasion, troc). Réparer, c'est éviter d'acheter du neuf." },
      { id: 'c', texte: 'Recycler', correcte: false, explication: "Le recyclage implique démontage, fragmentation et conversion en matériaux : le produit est détruit." },
      { id: 'd', texte: 'Un quatrième R distinct', correcte: false, explication: "Le cours ne définit que trois R ; la réparation est explicitement citée dans la définition de « Réduire »." },
    ],
    correction: "« Chaque fois que nous faisons réparer un appareil numérique, plutôt que d'en acheter un nouveau, nous réduisons les déchets. » Test : l'objet change-t-il de propriétaire ? Non → Réduire.",
  },
  {
    id: 'qz-bmc-limite', type: 'qcm', categorie: 'business-model', priorite: 1,
    enonce: "Quelle limite du BMC le cours souligne-t-il en premier ?",
    notions: ['bmc'],
    options: [
      { id: 'a', texte: 'Il est trop complexe à remplir', correcte: false, explication: "Le cours dit exactement l'inverse : il « présente l'avantage de la simplicité et d'une mise en œuvre facile et directe »." },
      { id: 'b', texte: "Il s'applique surtout à des entreprises monoactivité comme les start-up", correcte: true },
      { id: 'c', texte: 'Il ignore la proposition de valeur', correcte: false, explication: "La proposition de valeur est au contraire le bloc CENTRAL du Canvas." },
      { id: 'd', texte: 'Il ne montre pas les revenus', correcte: false, explication: "Les flux de revenus sont l'un des neuf blocs." },
    ],
    correction: "Trois limites explicites : monoactivité, néglige la concurrence, essentiellement statique. Le cours les donne AVANT le contenu — c'est un signal fort.",
  },
  {
    id: 'qz-donut-echec', type: 'qcm', categorie: 'durabilite', priorite: 1,
    enonce: "Selon le Donut, une entreprise qui réduit son empreinte numérique en excluant les seniors…",
    notions: ['donut', 'plancher-social', 'exclusion-indirecte'],
    options: [
      { id: 'a', texte: 'respecte le donut, puisque son impact baisse', correcte: false, explication: "Réduire le dépassement en créant un abaissement social n'est pas un progrès : le donut exige de rester entre les DEUX bords." },
      { id: 'b', texte: 'échange un dépassement écologique contre un abaissement social', correcte: true },
      { id: 'c', texte: 'applique la durabilité forte', correcte: false, explication: "La durabilité forte porte sur la non-substituabilité du capital naturel, pas sur un arbitrage entre social et environnemental." },
      { id: 'd', texte: "améliore son plancher social", correcte: false, explication: "Elle le dégrade : des besoins fondamentaux (accès aux services financiers) cessent d'être satisfaits pour une partie de la population." },
    ],
    correction: "« Un service allégé au point d'exclure certains publics ne respecte pas le donut, même s'il réduit ses impacts techniques. » C'est un déplacement du problème, pas de la durabilité.",
  },
  {
    id: 'qz-mission-bmc', type: 'qcm', categorie: 'business-model-durable', priorite: 1,
    enonce: "Pourquoi la mission porte-t-elle le numéro (0) dans le BMC durable ?",
    notions: ['bmc-durable', 'mission'],
    options: [
      { id: 'a', texte: "Parce qu'elle est optionnelle", correcte: false, explication: "C'est l'inverse : elle est le point de départ obligé du modèle." },
      { id: 'b', texte: "Parce qu'elle précède et conditionne tous les autres blocs", correcte: true },
      { id: 'c', texte: "Parce qu'elle ne génère aucun revenu", correcte: false, explication: "La numérotation ne renvoie pas au revenu mais à l'ordre d'analyse." },
      { id: 'd', texte: "Parce qu'elle a été ajoutée après les autres blocs", correcte: false, explication: "L'antériorité historique n'est pas le sujet : le 0 marque la priorité logique." },
    ],
    correction: "Au lieu de partir du marché (« quel besoin solvable puis-je servir ? »), on part de la raison d'être. La numérotation à 0 n'est pas décorative.",
  },
  {
    id: 'qz-privacy', type: 'qcm', categorie: 'rne', priorite: 1,
    enonce: "Une case de consentement décochée par défaut relève de…",
    notions: ['privacy-by-default', 'opt-in'],
    options: [
      { id: 'a', texte: 'privacy by design', correcte: false, explication: "By design concerne l'ARCHITECTURE du produit dès sa conception, pas l'état d'un réglage livré." },
      { id: 'b', texte: 'privacy by default', correcte: true },
      { id: 'c', texte: 'la minimisation des données', correcte: false, explication: "La minimisation porte sur la QUANTITÉ de données collectées, pas sur le mécanisme de consentement." },
      { id: 'd', texte: 'un dark pattern', correcte: false, explication: "Un dark pattern serait au contraire une case PRÉ-COCHÉE, qui vide le consentement de son sens." },
    ],
    correction: "By default = les paramètres les plus protecteurs sont activés d'origine, l'utilisateur est protégé même s'il ne touche à rien. L'opt-in en est l'application concrète.",
  },
  {
    id: 'qz-wcag-police', type: 'qcm', categorie: 'accessibilite', priorite: 1,
    enonce: "« La taille de police n'est pas personnalisable. » Quel principe WCAG est violé ?",
    notions: ['pour', 'wcag'],
    options: [
      { id: 'a', texte: 'Perceptible', correcte: true },
      { id: 'b', texte: 'Opérable', correcte: false, explication: "Opérable concerne la navigation et l'interaction (clavier, temps suffisant, zones cliquables), pas la perception du contenu." },
      { id: 'c', texte: 'Compréhensible', correcte: false, explication: "Compréhensible concerne le langage, la prévisibilité et les messages d'erreur." },
      { id: 'd', texte: 'Robuste', correcte: false, explication: "Robuste concerne la compatibilité avec les technologies d'assistance et la validité du code." },
    ],
    correction: "Perceptible : l'information doit pouvoir être PERÇUE — texte alternatif, contraste suffisant, sous-titres, taille de police ajustable, jamais d'information portée par la couleur seule.",
  },
  {
    id: 'qz-ocean-test', type: 'qcm', categorie: 'diagnostic-externe', priorite: 2,
    enonce: "Une entreprise ajoute des fonctionnalités premium et augmente son prix. Est-ce un océan bleu ?",
    notions: ['ocean-bleu', 'innovation-valeur'],
    options: [
      { id: 'a', texte: "Oui, elle crée de la valeur nouvelle", correcte: false, explication: "L'innovation-valeur exige de créer de la valeur ET de réduire ses coûts SIMULTANÉMENT." },
      { id: 'b', texte: "Non, c'est de la différenciation classique", correcte: true },
      { id: 'c', texte: "Oui, si les concurrents ne le font pas", correcte: false, explication: "L'absence d'imitation immédiate ne suffit pas : le test porte sur le couple valeur/coûts, pas sur la nouveauté." },
      { id: 'd', texte: "Non, car l'océan bleu suppose une baisse de prix", correcte: false, explication: "L'océan bleu n'impose pas de baisser le prix : il impose de baisser les COÛTS tout en augmentant la valeur." },
    ],
    correction: "Test de l'innovation-valeur : ma proposition augmente-t-elle la valeur client ET réduit-elle mes coûts ? Si elle ne fait qu'ajouter de la valeur en ajoutant du coût, ce n'est pas un océan bleu.",
  },
  {
    id: 'qz-approvisionnement', type: 'qcm', categorie: 'diagnostic-interne', priorite: 1,
    enonce: "« Négocier les contrats avec les fournisseurs de composants » relève de quelle activité ?",
    notions: ['approvisionnements', 'logistique-approvisionnement'],
    options: [
      { id: 'a', texte: "Logistique d'approvisionnement (activité principale)", correcte: false, explication: "La logistique d'approvisionnement RÉCEPTIONNE, stocke et manipule. Elle ne négocie pas." },
      { id: 'b', texte: 'Approvisionnements (activité de soutien)', correcte: true },
      { id: 'c', texte: 'Infrastructure de l\'entreprise', correcte: false, explication: "L'infrastructure couvre la direction générale, la comptabilité, le juridique et l'administratif." },
      { id: 'd', texte: 'Développement technologique', correcte: false, explication: "Le développement technologique couvre la R&D, les systèmes d'information et la gestion des connaissances." },
    ],
    correction: "Piège classique du cours : l'approvisionnement (soutien) NÉGOCIE et ACQUIERT ; la logistique d'approvisionnement (principale) RÉCEPTIONNE et MANIPULE.",
  },
  {
    id: 'qz-rebond-type', type: 'qcm', categorie: 'numerique', priorite: 2,
    enonce: "« Un serveur plus efficace : on héberge donc plus de services dessus. » Quel type d'effet rebond ?",
    notions: ['effet-rebond'],
    options: [
      { id: 'a', texte: 'Direct', correcte: true },
      { id: 'b', texte: 'Indirect', correcte: false, explication: "L'indirect suppose que l'argent ou le temps économisé soit dépensé AILLEURS, sur un autre poste." },
      { id: 'c', texte: 'De marché', correcte: false, explication: "L'effet de marché passe par une baisse des PRIX qui élargit la demande à l'échelle du secteur." },
      { id: 'd', texte: 'De croissance', correcte: false, explication: "L'effet de croissance opère à l'échelle macroéconomique, via la consommation totale de ressources." },
    ],
    correction: "Direct : le gain d'efficacité rend l'usage moins coûteux, donc on l'utilise davantage — sur le même poste.",
  },

  // ------------------------------------------------------ RÉPONSES MULTIPLES ----
  {
    id: 'qz-multi-pestel', type: 'multiple', categorie: 'diagnostic-externe', priorite: 1,
    enonce: "Parmi ces éléments, lesquels relèvent du PESTEL (et non de Porter) ?",
    notions: ['pestel', 'porter-five-forces'],
    options: [
      { id: 'a', texte: "L'inflation et le taux de chômage", correcte: true },
      { id: 'b', texte: 'Le nombre de concurrents directs', correcte: false, explication: "La concurrence directe relève de la rivalité, force de Porter — pas du facteur économique du PESTEL." },
      { id: 'c', texte: 'Une nouvelle réglementation sur les déchets électroniques', correcte: true },
      { id: 'd', texte: "Le pouvoir de négociation d'un fournisseur unique", correcte: false, explication: "C'est explicitement une force de Porter." },
      { id: 'e', texte: 'Le vieillissement de la population', correcte: true },
      { id: 'f', texte: "La facilité pour un client de changer de marque", correcte: false, explication: "Le coût de changement conditionne le pouvoir des clients : c'est Porter." },
    ],
    correction: "Test : ce fait touche-t-il tous les secteurs, ou seulement le mien ? Tous → PESTEL. Le mien → Porter.",
  },
  {
    id: 'qz-multi-immateriel', type: 'multiple', categorie: 'diagnostic-interne', priorite: 1,
    enonce: "Quelles ressources sont difficilement transférables et imitables, donc sources d'avantage durable ?",
    notions: ['transferabilite', 'ressources-intangibles'],
    options: [
      { id: 'a', texte: 'La réputation et la notoriété de la marque', correcte: true },
      { id: 'b', texte: 'Les fonds propres et la capacité d\'endettement', correcte: false, explication: "Ressources financières : tangibles et échangeables. N'importe quel concurrent capitalisé fait pareil." },
      { id: 'c', texte: 'Les routines organisationnelles et les procédures', correcte: true },
      { id: 'd', texte: 'Les équipements et bâtiments', correcte: false, explication: "Ressources physiques : tangibles et cessibles sur des marchés. Une usine s'achète." },
      { id: 'e', texte: 'Le savoir-faire technique et les brevets', correcte: true },
    ],
    correction: "Le tableau des six natures se lit comme un gradient, du plus achetable (physique, financier) au moins imitable (réputation). La valeur stratégique croît en descendant.",
  },
  {
    id: 'qz-multi-rne', type: 'multiple', categorie: 'rne', priorite: 1,
    enonce: "Quels bénéfices le Guide RNE attribue-t-il à une démarche de responsabilité numérique ?",
    notions: ['rne'],
    options: [
      { id: 'a', texte: 'Renforcer la confiance des clients, partenaires et collaborateurs', correcte: true },
      { id: 'b', texte: 'Anticiper les évolutions réglementaires', correcte: true },
      { id: 'c', texte: 'Supprimer toute obligation de conformité', correcte: false, explication: "La RNE ne supprime aucune obligation : elle permet de les anticiper, ce qui est très différent." },
      { id: 'd', texte: 'Réduire les coûts (énergie, équipements, licences)', correcte: true },
      { id: 'e', texte: 'Se différencier sur son marché', correcte: true },
      { id: 'f', texte: "Garantir une croissance des usages numériques", correcte: false, explication: "L'axe environnement de la RNE vise au contraire à questionner les usages : la sobriété est un de ses principes." },
    ],
    correction: "Chaque bénéfice se traduit dans un outil du cours : confiance → ressource de réputation ; anticipation → facteur légal ; risques → acceptabilité du SAF ; coûts → structure de coûts ; différenciation → option stratégique.",
  },
  {
    id: 'qz-multi-externalites', type: 'multiple', categorie: 'business-model-durable', priorite: 1,
    enonce: "Dans quels blocs du BMC inspecte-t-on pour repérer une externalité négative ?",
    notions: ['externalite-negative', 'bmc-durable'],
    options: [
      { id: 'a', texte: 'Ressources clés', correcte: true },
      { id: 'b', texte: 'Activités clés', correcte: true },
      { id: 'c', texte: 'Structure de coûts', correcte: true },
      { id: 'd', texte: 'Relations clients', correcte: false, explication: "C'est un bloc où l'on CONSTRUIT des impacts positifs (sensibilisation), pas où l'on repère des externalités négatives." },
      { id: 'e', texte: 'Canaux', correcte: false, explication: "Le cours localise les externalités du côté production ; les canaux relèvent du côté client." },
    ],
    correction: "Symétrie voulue par le cours : les externalités négatives se repèrent du côté PRODUCTION (gauche du Canvas), les impacts positifs se construisent du côté CLIENT et PARTENAIRES.",
  },

  // ------------------------------------------------------------ VRAI/FAUX ----
  {
    id: 'qz-vf-opportunite', type: 'vrai-faux', categorie: 'diagnostic', priorite: 1,
    enonce: "Une opportunité peut être une compétence interne de l'entreprise.",
    notions: ['opportunite', 'force'],
    options: [
      { id: 'v', texte: 'Vrai', correcte: false, explication: "L'opportunité est EXTERNE par définition. Une compétence interne est une FORCE. C'est l'erreur la plus dangereuse du cours." },
      { id: 'f', texte: 'Faux', correcte: true },
    ],
    correction: "Test infaillible : si l'entreprise disparaissait, cet élément existerait-il encore ? Oui → externe (opportunité/menace). Non → interne (force/faiblesse).",
  },
  {
    id: 'qz-vf-iso26000', type: 'vrai-faux', categorie: 'durabilite', priorite: 2,
    enonce: "ISO 26000 est une certification que l'entreprise peut obtenir.",
    notions: ['iso-durabilite'],
    options: [
      { id: 'v', texte: 'Vrai', correcte: false, explication: "ISO 26000 donne des LIGNES DIRECTRICES relatives à la responsabilité sociétale. Le cours la distingue explicitement d'ISO 14001, qui est une certification." },
      { id: 'f', texte: 'Faux', correcte: true },
    ],
    correction: "ISO 14001 : « définit les critères d'un système de management environnemental (certification) ». ISO 26000 : « lignes directrices relatives à la responsabilité sociétale ».",
  },
  {
    id: 'qz-vf-legal', type: 'vrai-faux', categorie: 'accessibilite', priorite: 1,
    enonce: "Si aucun manquement légal n'est constaté, l'entreprise ne court aucun risque lié à l'accessibilité.",
    notions: ['exclusion-indirecte', 'double-levier-accessibilite'],
    options: [
      { id: 'v', texte: 'Vrai', correcte: false, explication: "L'absence de manquement à une règle existante n'exclut ni l'exclusion indirecte, ni le risque futur quand la loi évolue (EAA, révision LHand). Le risque est stratégique : perte de clientèle, de réputation et de marché." },
      { id: 'f', texte: 'Faux', correcte: true },
    ],
    correction: "« Ici le risque n'est pas juridique mais stratégique. » C'est le cœur du cas SilverDigital et la distinction centrale du chapitre.",
  },
  {
    id: 'qz-vf-numerique', type: 'vrai-faux', categorie: 'numerique', priorite: 1,
    enonce: "Le numérique est immatériel, son impact environnemental est donc marginal.",
    notions: ['transformation-numerique', 'trois-postes-numerique'],
    options: [
      { id: 'v', texte: 'Vrai', correcte: false, explication: "« Le premier fait à rappeler est que le numérique n'est pas immatériel. » Il repose sur trois postes matériels : terminaux (~50 % de l'impact), data centers (46 %), réseaux (4 %)." },
      { id: 'f', texte: 'Faux', correcte: true },
    ],
    correction: "Le numérique est présenté par le cours comme matériel, énergivore, politique et addictif — à rebours de l'image d'immatérialité.",
  },
  {
    id: 'qz-vf-porter-liste', type: 'vrai-faux', categorie: 'diagnostic-externe', priorite: 1,
    enonce: "Le modèle des 5 forces sert à lister les concurrents d'une entreprise.",
    notions: ['porter-five-forces'],
    options: [
      { id: 'v', texte: 'Vrai', correcte: false, explication: "C'est LE piège numéro un du chapitre. Porter mesure l'ATTRACTIVITÉ d'un secteur — sa capacité à laisser de la rentabilité — pas le nombre d'acteurs." },
      { id: 'f', texte: 'Faux', correcte: true },
    ],
    correction: "Les cinq forces sont cinq prétendants au partage de la valeur créée. La rentabilité qui reste à l'entreprise est celle que les cinq autres n'ont pas captée.",
  },
  {
    id: 'qz-vf-boucle', type: 'vrai-faux', categorie: 'numerique', priorite: 2,
    enonce: "Une « rétroaction positive » désigne une boucle bénéfique pour le système.",
    notions: ['boucle-retroaction', 'pensee-systemique'],
    options: [
      { id: 'v', texte: 'Vrai', correcte: false, explication: "En systémique, « positive » signifie qui S'AUTO-AMPLIFIE — donc explosive et non régulée. C'est le contraire d'un système stable." },
      { id: 'f', texte: 'Faux', correcte: true },
    ],
    correction: "Plus d'infrastructures → plus de services → plus d'usages → plus de besoins ressentis → plus d'infrastructures. Rien dans cette boucle ne la freine.",
  },

  // ---------------------------------------------------------- ASSOCIATION ----
  {
    id: 'qz-asso-outils', type: 'association', categorie: 'diagnostic', priorite: 1,
    enonce: "Associez chaque outil à son niveau d'analyse.",
    notions: ['pestel', 'porter-five-forces', 'chaine-de-valeur', 'swot', 'saf'],
    paires: [
      { gauche: 'PESTEL', droite: 'Macro-environnement' },
      { gauche: 'Porter', droite: 'Industrie / espace concurrentiel' },
      { gauche: 'Chaîne de valeur', droite: 'Intérieur de l’entreprise' },
      { gauche: 'SWOT', droite: 'Synthèse externe + interne' },
      { gauche: 'SAF', droite: 'Évaluation d’une option' },
    ],
    correction: "C'est la lecture directe du schéma des strates : macro → industrie → espace concurrentiel → entreprise, puis synthèse et évaluation.",
  },
  {
    id: 'qz-asso-saf', type: 'association', categorie: 'choix', priorite: 1,
    enonce: "Associez chaque critère du SAF à son outil (version du cours).",
    notions: ['saf', 'souhaitabilite', 'acceptabilite', 'faisabilite'],
    paires: [
      { gauche: 'Souhaitabilité', droite: 'SWOT' },
      { gauche: 'Acceptabilité', droite: 'Analyse des parties prenantes + des risques' },
      { gauche: 'Faisabilité', droite: 'PESTEL' },
    ],
    correction: "Restitue impérativement ces associations telles que le cours les pose : c'est cela qui est attendu à l'examen.",
  },
  {
    id: 'qz-asso-durabilite', type: 'association', categorie: 'durabilite', priorite: 2,
    enonce: "Associez chaque modèle à son auteur ou sa source.",
    notions: ['trois-cercles-elkington', 'mickey-mouse-model', 'wedding-cake', 'limites-planetaires', 'donut'],
    paires: [
      { gauche: 'Les 3 cercles du développement durable', droite: 'Elkington, 1997' },
      { gauche: 'Mickey Mouse Model', droite: 'Peet, 2009' },
      { gauche: 'Wedding Cake des ODD', droite: 'Stockholm Resilience Centre' },
      { gauche: 'Limites planétaires', droite: 'Rockström, 2009' },
      { gauche: 'Théorie du Donut', droite: 'Kate Raworth, 2017' },
    ],
    correction: "La progression 3 cercles → Mickey Mouse → Wedding Cake raconte le passage de la durabilité faible à la durabilité forte.",
  },
  {
    id: 'qz-asso-sobriete', type: 'association', categorie: 'numerique', priorite: 1,
    enonce: "Associez les trois logiques parallèles du cours.",
    notions: ['sobriete-numerique', 'trois-r', 'achats-it-responsables'],
    paires: [
      { gauche: 'Questionner', droite: 'Réduire / Acheter moins' },
      { gauche: 'Transférer', droite: 'Réutiliser / Acheter mieux' },
      { gauche: 'Améliorer', droite: 'Recycler / Utiliser mieux et plus longtemps' },
    ],
    correction: "La même structure logique traverse tout le cours : agir sur le BESOIN avant d'agir sur la technique. Si tu ne retiens qu'une idée de la partie durabilité, c'est celle-là.",
  },
  {
    id: 'qz-asso-cas', type: 'association', categorie: 'diagnostic', priorite: 2,
    enonce: "Associez chaque cas du cours à l'outil qu'il illustre le mieux.",
    notions: ['parties-prenantes', 'pestel', 'porter-five-forces', 'chaine-de-valeur', 'bmc', 'accessibilite-numerique'],
    paires: [
      { gauche: 'CIO', droite: 'Analyse des parties prenantes' },
      { gauche: 'Fukushima', droite: 'PESTEL' },
      { gauche: 'Eaux embouteillées', droite: 'Porter et toile 0-5' },
      { gauche: 'Smart', droite: 'Chaîne de valeur' },
      { gauche: 'Oncle Hansi', droite: 'Business Model et BMC' },
      { gauche: 'SilverDigital', droite: 'Accessibilité et RNE' },
    ],
    correction: "Six cas, six outils : c'est la carte mentale la plus rentable à l'oral, car chaque cas te donne un exemple concret prêt à citer.",
  },

  // ---------------------------------------------------- CLASSEMENT / ORDRE ----
  {
    id: 'qz-ordre-3r', type: 'classement', categorie: 'circularite', priorite: 1,
    enonce: "Remettez les 3R dans le bon ordre de priorité.",
    notions: ['trois-r', 'economie-circulaire'],
    ordreCorrect: ['Réduire', 'Réutiliser', 'Recycler'],
    justificationOrdre:
      "Réduire : le produit n'est jamais fabriqué → 100 % d'impact évité. Réutiliser : le produit garde sa forme et sa valeur, seule l'énergie de transport et de reconditionnement est dépensée. Recycler : le produit est détruit, on ne récupère que la matière, avec des procédés énergivores et des pertes.",
    correction: "Le cours le dit textuellement : « tout cela dépend des efforts de réduction et de réutilisation, PUIS ENFIN SEULEMENT de recyclage ».",
  },
  {
    id: 'qz-ordre-demarche', type: 'ordonnancement', categorie: 'fondements', priorite: 1,
    enonce: "Remettez ces étapes dans l'ordre du raisonnement stratégique.",
    notions: ['demarche-strategique', 'pestel', 'porter-five-forces', 'swot', 'saf'],
    ordreCorrect: ['PESTEL', 'Porter', 'Diagnostic interne', 'SWOT', 'Options', 'SAF', 'Décision'],
    justificationOrdre:
      "Le SWOT est la SYNTHÈSE des diagnostics : il ne peut pas venir avant. Le SAF ÉVALUE des options : il ne peut pas venir avant qu'elles existent. Et le PESTEL (macro) éclaire Porter (micro).",
    correction: "« Avant de se lancer dans la mise en œuvre d'une stratégie, il s'agit de l'évaluer » — le SAF est un test avant décollage, pas un bilan.",
  },
  {
    id: 'qz-ordre-cv', type: 'ordonnancement', categorie: 'diagnostic-interne', priorite: 1,
    enonce: "Remettez les 5 activités principales de la chaîne de valeur dans l'ordre.",
    notions: ['activites-principales', 'chaine-de-valeur'],
    ordreCorrect: [
      "Logistique d'approvisionnement",
      'Production / fabrication',
      'Logistique de commercialisation',
      'Marketing et ventes',
      'Services',
    ],
    justificationOrdre:
      "C'est le flux physique du produit : ce qui entre est reçu, transformé, livré, vendu, puis accompagné. La flèche du schéma de Porter est orientée : chaque activité ajoute valeur et coût, la marge est le solde.",
    correction: "Attention à ne pas confondre la logistique d'approvisionnement (activité PRINCIPALE) avec l'approvisionnement (activité de SOUTIEN).",
  },
  {
    id: 'qz-ordre-charte', type: 'ordonnancement', categorie: 'rne', priorite: 2,
    enonce: "Remettez dans l'ordre les 5 étapes de mise en place d'une charte numérique.",
    notions: ['charte-numerique'],
    ordreCorrect: ['Identifier les enjeux prioritaires', 'Impliquer les équipes', 'Formaliser des engagements', 'Diffuser', 'Faire vivre'],
    justificationOrdre:
      "L'étape 2 est celle à souligner : la charte se rédige AVEC les équipes, pas pour elles. C'est ce qui la distingue d'un règlement descendant et ce qui conditionne son appropriation.",
    correction: "Lien direct avec l'analyse des parties prenantes : les collaborateurs sont traités en « engager avec attention » (co-décision), pas en « informer ».",
  },
  {
    id: 'qz-ordre-modeles', type: 'ordonnancement', categorie: 'durabilite', priorite: 2,
    enonce: "Remettez dans l'ordre la progression des cadres conceptuels de la durabilité.",
    notions: ['trois-cercles-elkington', 'mickey-mouse-model', 'wedding-cake'],
    ordreCorrect: ['3 cercles (Elkington 1997)', 'Mickey Mouse Model (Peet 2009)', 'Wedding Cake (Stockholm)'],
    justificationOrdre:
      "Description (les trois dimensions à égalité) → critique (en réalité l'économique domine) → correction (hiérarchie imbriquée : la biosphère conditionne tout).",
    correction: "Cette progression montre le passage de la durabilité faible à la durabilité forte. C'est un excellent contenu d'oral.",
  },
  {
    id: 'qz-ordre-achats', type: 'ordonnancement', categorie: 'circularite', priorite: 2,
    enonce: "Remettez dans l'ordre le processus des achats responsables.",
    notions: ['achats-it-responsables'],
    ordreCorrect: ['Besoin', 'Analyses (risques, marché)', 'Critères', 'Preuves (labels, certifications)', 'Utilisation', 'Fin de vie'],
    justificationOrdre:
      "Tout commence par le BESOIN, pas par le produit. L'appel d'offres n'occupe que la zone centrale : le levier le plus puissant se situe AVANT, la durée de vie se joue APRÈS. Et la fin de vie relance l'analyse du besoin.",
    correction: "Analyses → Critères → Preuves : sans preuve, un critère d'achat reste déclaratif.",
  },

  // ------------------------------------------------------- CATÉGORISATION ----
  {
    id: 'qz-cat-swot', type: 'categorisation', categorie: 'diagnostic', priorite: 1,
    enonce: "Classez ces éléments du cas SilverDigital dans les quatre cases du SWOT.",
    notions: ['swot', 'force', 'faiblesse', 'opportunite', 'menace'],
    categoriesCibles: [
      { id: 'F', libelle: 'Force' },
      { id: 'Fa', libelle: 'Faiblesse' },
      { id: 'O', libelle: 'Opportunité' },
      { id: 'M', libelle: 'Menace' },
    ],
    elements: [
      { texte: '+15 % de marge opérationnelle', cible: 'F', explication: "Résultat interne obtenu par l'entreprise." },
      { texte: 'Base de clients fidèles depuis 20 ans', cible: 'F', explication: "Ressource de réputation, interne et difficilement imitable." },
      { texte: 'Taille de police non personnalisable', cible: 'Fa', explication: "Défaut de conception interne, corrigeable par l'entreprise." },
      { texte: "4 étapes et 9 minutes pour joindre un humain", cible: 'Fa', explication: "Choix d'organisation interne." },
      { texte: 'Vieillissement de la population genevoise', cible: 'O', explication: "Évolution démographique externe, exploitable si l'entreprise s'adapte." },
      { texte: 'European Accessibility Act, juin 2025', cible: 'O', explication: "Marché de la mise en conformité et possibilité de devancer l'obligation — externe." },
      { texte: '−12 % de clients de plus de 65 ans', cible: 'M', explication: "Érosion d'un segment : c'est un fait de marché, donc externe." },
      { texte: 'Risque réputationnel relayé par la presse', cible: 'M', explication: "Réaction de l'environnement, hors du contrôle direct de l'entreprise." },
    ],
    correction: "Test à appliquer à chaque ligne : si l'entreprise disparaissait, cet élément existerait-il encore ? Oui → externe (O/M). Non → interne (F/Fa).",
  },
  {
    id: 'qz-cat-pestel', type: 'categorisation', categorie: 'diagnostic-externe', priorite: 1,
    enonce: "Classez ces faits dans les six facteurs du PESTEL.",
    notions: ['pestel', 'facteur-politique', 'facteur-economique', 'facteur-socioculturel', 'facteur-technologique', 'facteur-environnemental-ethique', 'facteur-legal'],
    categoriesCibles: [
      { id: 'P', libelle: 'Politique' },
      { id: 'E', libelle: 'Économique' },
      { id: 'S', libelle: 'Socioculturel' },
      { id: 'T', libelle: 'Technologique' },
      { id: 'EE', libelle: 'Environnemental et éthique' },
      { id: 'L', libelle: 'Légal' },
    ],
    elements: [
      { texte: "Décision de sortie du nucléaire à l'horizon 2022", cible: 'P', explication: "Décision gouvernementale : orientation politique." },
      { texte: "Le prix moyen de l'énergie augmente", cible: 'E', explication: "Développement économique : coût des facteurs de production." },
      { texte: 'Un climat anxiogène pousse des personnes vers les mouvements écologiques', cible: 'S', explication: "Évolution des mentalités et des comportements collectifs." },
      { texte: "Les normes électriques diffèrent d'un pays à l'autre, ce qui ajoute des coûts d'adaptation", cible: 'T', explication: "Hétérogénéité des normes et disponibilité des technologies." },
      { texte: "Des groupes environnementaux dénoncent le manque de leçons tirées de Tchernobyl", cible: 'EE', explication: "Éthique des affaires et réaction de l'opinion publique amplifiée par les médias." },
      { texte: "Les ampoules inférieures aux normes ne peuvent plus être vendues dans l'UE depuis septembre 2012", cible: 'L', explication: "Règle juridique assortie d'un dispositif de contrôle." },
      { texte: 'Subventions accordées aux champions nationaux', cible: 'P', explication: "L'État protège son marché — préfigure la 6ᵉ force de Porter." },
      { texte: "Le bien-être animal devient un critère d'achat", cible: 'EE', explication: "Dimension éthique du facteur fusionné environnemental et éthique." },
    ],
    correction: "Le « E » du cours est fusionné : il couvre à la fois l'écologique/environnemental et l'éthique. Traite systématiquement les deux dimensions.",
  },
  {
    id: 'qz-cat-saf', type: 'categorisation', categorie: 'choix', priorite: 1,
    enonce: "Classez ces affirmations dans les trois critères du SAF.",
    notions: ['saf', 'souhaitabilite', 'acceptabilite', 'faisabilite'],
    categoriesCibles: [
      { id: 'S', libelle: 'Souhaitabilité' },
      { id: 'A', libelle: 'Acceptabilité' },
      { id: 'F', libelle: 'Faisabilité' },
    ],
    elements: [
      { texte: "L'option répond directement à la menace identifiée au SWOT", cible: 'S', explication: "Correspondance entre l'environnement et les ressources." },
      { texte: "Les actionnaires refuseront de dégrader la marge", cible: 'A', explication: "Attractivité auprès d'une partie prenante puissante et concernée." },
      { texte: "Le niveau de risque est-il tolérable ?", cible: 'A', explication: "Question explicite du critère d'acceptabilité." },
      { texte: "Dispose-t-on des ressources financières, ou peut-on les acquérir ?", cible: 'F', explication: "Première question du critère de faisabilité." },
      { texte: "Aucune contrainte légale ne s'y oppose", cible: 'F', explication: "Contraintes exogènes, notamment légales." },
      { texte: "L'option exploite l'opportunité du vieillissement de la population", cible: 'S', explication: "Prise en compte des opportunités clés." },
      { texte: "Les compétences de conseil existent-elles en interne ?", cible: 'F', explication: "Ressources humaines et savoir-faire." },
    ],
    correction: "Souhaitabilité = pertinence au regard du diagnostic. Acceptabilité = adhésion des acteurs et couple rendement/risque. Faisabilité = moyens et droit.",
  },
  {
    id: 'qz-cat-bmc', type: 'categorisation', categorie: 'business-model', priorite: 1,
    enonce: "Classez ces éléments du cas Oncle Hansi dans les blocs du BMC.",
    notions: ['bmc', 'segments-clients', 'proposition-de-valeur', 'canaux', 'flux-revenus', 'ressources-cles', 'partenaires-cles', 'structure-couts'],
    categoriesCibles: [
      { id: 'seg', libelle: 'Segments de clients' },
      { id: 'pv', libelle: 'Proposition de valeur' },
      { id: 'can', libelle: 'Canaux' },
      { id: 'rev', libelle: 'Flux de revenus' },
      { id: 'res', libelle: 'Ressources clés' },
      { id: 'part', libelle: 'Partenaires clés' },
      { id: 'cout', libelle: 'Structure de coûts' },
    ],
    elements: [
      { texte: "Les droits de l'œuvre de Jean-Jacques Waltz, acquis en 2012", cible: 'res', explication: "Ce que l'entreprise POSSÈDE et qui fonde tout le modèle." },
      { texte: '24 entreprises alsaciennes adhérentes', cible: 'part', explication: "Le réseau grâce auquel le modèle fonctionne." },
      { texte: 'Les enseignes de grande distribution', cible: 'seg', explication: "Segment B2B — c'est le segment que l'on oublie le plus souvent." },
      { texte: 'Cotisations d’adhésion et redevances sur les ventes', cible: 'rev', explication: "D'où vient l'argent, et comment il est payé." },
      { texte: 'Les corners « Oncle Hansi » en magasin', cible: 'can', explication: "Comment l'entreprise atteint le consommateur." },
      { texte: 'Un label alsacien : qualité, locavorisme, identité régionale', cible: 'pv', explication: "La promesse — unique, pour des clients différents." },
      { texte: 'La logistique reste à la charge des entreprises adhérentes', cible: 'cout', explication: "Décision d'architecture : externalisation, structure la plus légère possible." },
      { texte: 'Une dizaine de salariés', cible: 'cout', explication: "Poids de la structure : le modèle est asset-light." },
    ],
    correction: "Méthode générale : pour chaque phrase du cas, demande-toi à quel bloc elle répond. Un cas bien lu remplit le Canvas presque intégralement.",
  },
  {
    id: 'qz-cat-obstacles', type: 'categorisation', categorie: 'accessibilite', priorite: 1,
    enonce: "Classez les obstacles de SilverDigital par famille.",
    notions: ['exclusion-indirecte', 'accessibilite-numerique'],
    categoriesCibles: [
      { id: 'tech', libelle: 'Technique' },
      { id: 'ergo', libelle: 'Ergonomique' },
      { id: 'orga', libelle: 'Organisationnel' },
      { id: 'strat', libelle: 'Stratégique' },
    ],
    elements: [
      { texte: 'Taille de police non modifiable', cible: 'tech', explication: "Défaut de mise en œuvre technique de l'interface." },
      { texte: 'Double authentification rigide, sans alternative', cible: 'tech', explication: "Contrainte technique imposée sans voie de contournement." },
      { texte: 'Navigation complexe dans l’application', cible: 'ergo', explication: "Problème de conception du parcours utilisateur." },
      { texte: 'Chatbot dont les réponses ne sont pas comprises', cible: 'ergo', explication: "Défaut de compréhensibilité du dialogue proposé." },
      { texte: 'Suppression des guichets physiques', cible: 'orga', explication: "Décision d'organisation qui supprime un canal humain." },
      { texte: 'Délai moyen de 9 minutes pour joindre un agent', cible: 'orga', explication: "Dimensionnement du service, pas un défaut de code." },
      { texte: 'Le choix « Digital First » privilégie les moins de 40 ans', cible: 'strat', explication: "Arbitrage de direction, en amont de toutes les autres causes." },
    ],
    correction: "Classer les obstacles est explicitement demandé par les consignes du cas. Le niveau stratégique est le plus important : il explique tous les autres.",
  },

  // -------------------------------------------------------- TEXTE À TROUS ----
  {
    id: 'qz-trous-swot', type: 'texte-a-trous', categorie: 'diagnostic', priorite: 1,
    enonce: "Complétez la formule d'examen sur le SWOT.",
    notions: ['swot'],
    segments: ["Le SWOT n'est pas un outil de ", null, ", c'est un outil de ", null, ' et de confrontation.'],
    reponses: ['collecte', 'synthèse'],
    propositions: ['collecte', 'synthèse', 'décision', 'mesure', 'prévision'],
    correction: "Il ne vaut que par la qualité des analyses qui l'alimentent — PESTEL et Porter à l'externe, ressources, compétences et chaîne de valeur à l'interne.",
  },
  {
    id: 'qz-trous-arbitrage', type: 'texte-a-trous', categorie: 'pilotage', priorite: 1,
    enonce: "Complétez la formule de conclusion.",
    notions: ['tensions-strategiques'],
    segments: ['Le véritable arbitrage se situe entre ', null, ' et ', null, '.'],
    reponses: ['le court terme', 'le long terme'],
    propositions: ['le court terme', 'le long terme', 'le prix', 'la qualité', 'l’offre'],
    correction: "Une bonne conclusion prend position ET nomme la tension. Autres tensions récurrentes : rentabilité / inclusion, efficacité / effet rebond, croissance / limites planétaires.",
  },
  {
    id: 'qz-trous-sobriete', type: 'texte-a-trous', categorie: 'numerique', priorite: 1,
    enonce: "Complétez la définition de la sobriété numérique.",
    notions: ['sobriete-numerique'],
    segments: ['Sobriété : ', null, ' les besoins en ', null, ' intention. Lucidité : penser les conséquences ', null, ' et indirectes.'],
    reponses: ['questionner', 'première', 'directes'],
    propositions: ['questionner', 'première', 'directes', 'optimiser', 'dernière', 'techniques'],
    correction: "Pas en dernier recours, pas après avoir optimisé : d'abord. Le processus courant fait l'inverse (Améliorer → Transférer → Questionner), et c'est pourquoi l'efficacité seule échoue.",
  },
  {
    id: 'qz-trous-externalite', type: 'texte-a-trous', categorie: 'diagnostic-interne', priorite: 1,
    enonce: "Complétez la définition de l'externalité négative (mots exacts du cours).",
    notions: ['externalite-negative'],
    segments: ['Un impact négatif représente un coût ', null, ' ', null, " à d'autres individus ou à la société."],
    reponses: ['non intentionnel', 'imposé'],
    propositions: ['non intentionnel', 'imposé', 'volontaire', 'négocié', 'comptabilisé'],
    correction: "Le mot « imposé » est essentiel : la société paie un coût qu'elle n'a pas choisi et qui n'apparaît pas dans les comptes de l'entreprise.",
  },
  {
    id: 'qz-trous-risque', type: 'texte-a-trous', categorie: 'accessibilite', priorite: 1,
    enonce: "Complétez la phrase-clé du cas SilverDigital.",
    notions: ['exclusion-indirecte'],
    segments: ["Ici le risque n'est pas ", null, ' mais ', null, '.'],
    reponses: ['juridique', 'stratégique'],
    propositions: ['juridique', 'stratégique', 'financier', 'technique', 'réputationnel'],
    correction: "Aucune loi n'est enfreinte, mais la perte de clientèle, de réputation et de marché constitue un risque stratégique majeur.",
  },
  {
    id: 'qz-trous-porter', type: 'texte-a-trous', categorie: 'diagnostic-externe', priorite: 1,
    enonce: "Complétez la logique économique de Porter.",
    notions: ['porter-five-forces', 'profit-prix-couts'],
    segments: ['Plus une force est puissante, plus la pression sur les prix ou les coûts est élevée, et ', null, ' le secteur est ', null, '. Équation : Profit = ', null, ' − Coûts.'],
    reponses: ['moins', 'attrayant', 'Prix'],
    propositions: ['moins', 'plus', 'attrayant', 'risqué', 'Prix', 'Revenus'],
    correction: "Chaque force a « un lien direct, clair et prévisible avec la rentabilité de tout secteur ». La toile grande = secteur peu attractif.",
  },
  {
    id: 'qz-trous-durabilite', type: 'texte-a-trous', categorie: 'durabilite', priorite: 1,
    enonce: "Complétez la définition de la durabilité (Agenda 2030).",
    notions: ['durabilite'],
    segments: ['Un fonctionnement pouvant satisfaire les besoins de ', null, " les individus, aujourd'hui et ", null, ', ici et ', null, ', dans le respect des ', null, '.'],
    reponses: ['tous', 'demain', 'ailleurs', 'limites planétaires'],
    propositions: ['tous', 'certains', 'demain', 'hier', 'ailleurs', 'chez nous', 'limites planétaires', 'objectifs financiers'],
    correction: "Cette seule phrase contient le plancher social (besoins de tous) et le plafond écologique (limites planétaires) — c'est-à-dire le Donut.",
  },
  {
    id: 'qz-trous-3u', type: 'texte-a-trous', categorie: 'rne', priorite: 2,
    enonce: "Complétez les 3U de la charte INR.",
    notions: ['trois-u'],
    segments: ['Les services numériques doivent être ', null, ', ', null, ' et ', null, '.'],
    reponses: ['Utiles', 'Utilisables', 'Utilisés'],
    propositions: ['Utiles', 'Utilisables', 'Utilisés', 'Universels', 'Uniformes'],
    correction: "Un service qui échoue à l'un des trois U mobilise des ressources sans créer de valeur. SilverDigital : Utile ✅, Utilisable ❌, donc Utilisé ❌ par 12 % de clientèle perdue.",
  },
]
