import type { Relation } from './types'

/**
 * RELATIONS ENTRE NOTIONS
 * =======================
 *
 * Chaque relation est déclarée **dans un seul sens** (le sens canonique).
 * Le sens inverse est dérivé automatiquement par `packages/domain/src/graph.ts`
 * à partir de `metaRelations[].inverse` : déclarer « PESTEL ALIMENTE SWOT » suffit
 * pour que la fiche SWOT affiche « Est alimenté par : PESTEL ».
 *
 * Une relation sans `description` n'apprend rien. La validation la refuse.
 */
export const relations: Relation[] = [
  // -------------------------------------------------------------------------
  // Fondements : la trajectoire vision → contrôle
  // -------------------------------------------------------------------------
  { source: 'vision', target: 'mission', type: 'PRECEDE', description: "La vision formalise l'avenir ; la mission en explicite la finalité aux parties prenantes." },
  { source: 'mission', target: 'valeurs', type: 'PRECEDE', description: "La mission dit pourquoi l'organisation existe ; les valeurs disent ce qu'il est possible de faire pour y parvenir." },
  { source: 'valeurs', target: 'buts-objectifs', type: 'PRECEDE', description: "Les valeurs bornent le champ des buts et objectifs acceptables." },
  { source: 'buts-objectifs', target: 'plan-action', type: 'PRECEDE', description: "Les objectifs quantitatifs se traduisent en actions concrètes." },
  { source: 'plan-action', target: 'controle', type: 'PRECEDE', description: "Le contrôle vérifie la bonne exécution des actions pour s'assurer de la réalisation des objectifs." },
  { source: 'plan-action', target: 'kpi', type: 'UTILISE', description: "L'alignement se vérifie par des indicateurs : chaque action doit servir un objectif mesuré." },
  { source: 'controle', target: 'kpi', type: 'UTILISE', description: "Le pilotage passe par des reportings réguliers utilisant des mesures financières et quantitatives." },
  { source: 'valeurs', target: 'charte-numerique', type: 'PEUT_CONDUIRE_A', description: "La charte numérique est l'héritière directe des valeurs : un cadre disant ce qui est acceptable et ce qui ne l'est pas dans l'usage du numérique." },
  { source: 'gouvernance', target: 'parties-prenantes', type: 'UTILISE', description: "Le cours introduit l'analyse des parties prenantes DANS la section gouvernance : comprendre qui décide et qui influence." },
  { source: 'gouvernance', target: 'gouvernance-donnees', type: 'CONTIENT', description: "La gouvernance des données est une déclinaison sectorielle de la gouvernance de l'entreprise." },
  { source: 'gouvernance', target: 'gouvernance-numerique-roles', type: 'CONTIENT', description: "Les rôles DPO, CISO, Accessibility Officer sont l'organisation concrète de la gouvernance numérique." },
  { source: 'strategie', target: 'niveaux-strategiques', type: 'CONTIENT', description: "La stratégie se décline à deux niveaux : corporate (où jouer) et business (comment gagner)." },
  { source: 'strategie', target: 'avantage-concurrentiel-durable', type: 'PEUT_CONDUIRE_A', description: "La stratégie vise à obtenir un avantage concurrentiel de façon durable, créateur de valeur pour les parties prenantes." },
  { source: 'strategie', target: 'business-model', type: 'NE_PAS_CONFONDRE', description: "La stratégie choisit le combat (où aller, contre qui, sur 3 à 10 ans) ; le business model est la machine qui le mène (comment ça fonctionne et comment on gagne de l'argent)." },
  { source: 'bonne-strategie', target: 'strategie', type: 'FAIT_PARTIE_DE', description: "Les six critères d'une bonne stratégie servent de grille d'évaluation d'une recommandation." },
  { source: 'avantage-concurrentiel', target: 'avantage-concurrentiel-durable', type: 'PRECEDE', description: "L'avantage devient durable lorsqu'il se maintient dans le temps, ce qui suppose des ressources peu transférables." },
  { source: 'demarche-strategique', target: 'perimetre', type: 'PRECEDE', description: "Définir le périmètre est la première puce de l'analyse de l'environnement : sans lui, un PESTEL devient une liste d'actualités." },
  { source: 'demarche-strategique', target: 'parties-prenantes', type: 'UTILISE', description: "« C'est le début de toute analyse pour réaliser un plan » — les parties prenantes viennent avant le diagnostic." },
  { source: 'demarche-strategique', target: 'diagnostic-strategique', type: 'CONTIENT', description: "Le diagnostic est l'étape 2 de la démarche : externe et interne." },
  { source: 'demarche-strategique', target: 'saf', type: 'CONTIENT', description: "L'évaluation SAF est l'étape 6, avant l'adaptation du business model." },
  { source: 'strates-environnement', target: 'pestel', type: 'CONTIENT', description: "La strate macroéconomique (facteurs généraux) est le territoire du PESTEL." },
  { source: 'strates-environnement', target: 'porter-five-forces', type: 'CONTIENT', description: "La strate « espace concurrentiel » (concurrents, fournisseurs, clients, entrants, substituts) est le territoire de Porter." },
  { source: 'strates-environnement', target: 'diagnostic-interne', type: 'CONTIENT', description: "La strate la plus intérieure — l'entreprise — est le territoire du diagnostic interne." },
  { source: 'strates-environnement', target: 'facteurs-cles-succes', type: 'CONTIENT', description: "La strate « industrie » est celle des facteurs clés de succès, charnière entre PESTEL et Porter." },
  { source: 'facteurs-cles-succes', target: 'das', type: 'DEPEND_DE', description: "Chaque domaine d'activité stratégique a ses propres concurrents et ses propres facteurs clés de succès." },
  { source: 'perimetre', target: 'perimetre-numerique', type: 'ILLUSTRE', description: "Définir le périmètre avant de citer un chiffre vaut pour la stratégie comme pour la mesure de l'impact du numérique." },

  // -------------------------------------------------------------------------
  // Parties prenantes
  // -------------------------------------------------------------------------
  { source: 'parties-prenantes', target: 'matrice-pouvoir-interet', type: 'UTILISE', description: "Après avoir listé et évalué les acteurs, on les positionne dans la matrice pouvoir × intérêt pour en déduire quatre traitements différents." },
  { source: 'parties-prenantes', target: 'acceptabilite', type: 'ALIMENTE', description: "Le critère d'Acceptabilité du SAF porte sur l'attractivité de la stratégie auprès des parties prenantes, en tenant compte de leurs intérêts et pouvoirs d'influence." },
  { source: 'parties-prenantes', target: 'conflit-interets', type: 'PEUT_CONDUIRE_A', description: "Quand l'intérêt personnel d'un acteur puissant diverge de celui de l'organisation, le traitement n'est plus la communication mais la conception de processus." },
  { source: 'parties-prenantes', target: 'rne', type: 'ALIMENTE', description: "Le Guide RNE fait de la confiance des clients, partenaires et collaborateurs un bénéfice central : la RNE est une politique de parties prenantes." },
  { source: 'parties-prenantes', target: 'durabilite', type: 'COMPLETE', description: "La durabilité élargit le cercle des parties prenantes aux acteurs non marchands : environnement, société, générations futures." },
  { source: 'matrice-pouvoir-interet', target: 'charte-numerique', type: 'EST_APPLIQUE_DANS', description: "La charte se rédigeant collectivement, les collaborateurs sont traités en « engager avec attention » (co-décision), pas en « informer »." },

  // -------------------------------------------------------------------------
  // Diagnostic et SWOT
  // -------------------------------------------------------------------------
  { source: 'diagnostic-strategique', target: 'diagnostic-externe', type: 'CONTIENT', description: "Le diagnostic complet a deux volets ; l'externe analyse ce qui arrive à l'entreprise." },
  { source: 'diagnostic-strategique', target: 'diagnostic-interne', type: 'CONTIENT', description: "Le second volet analyse ce que l'entreprise possède et sait faire." },
  { source: 'diagnostic-externe', target: 'diagnostic-interne', type: 'COMPLETE', description: "Une opportunité n'en est une que si l'on a les ressources pour la saisir ; une menace n'est fatale que sans les compétences pour l'absorber." },
  { source: 'diagnostic-externe', target: 'pestel', type: 'UTILISE', description: "Le PESTEL est l'outil d'analyse principal de l'environnement macroéconomique et sociétal." },
  { source: 'diagnostic-externe', target: 'porter-five-forces', type: 'UTILISE', description: "Les 5 forces sont l'outil d'analyse de l'industrie et de l'environnement concurrentiel." },
  { source: 'diagnostic-interne', target: 'ressources', type: 'UTILISE', description: "Étape 2 du diagnostic interne : analyse des ressources matérielles et immatérielles." },
  { source: 'diagnostic-interne', target: 'competences', type: 'UTILISE', description: "Les compétences décrivent ce que l'entreprise sait faire de ses ressources." },
  { source: 'diagnostic-interne', target: 'chaine-de-valeur', type: 'UTILISE', description: "Étape 3 du diagnostic interne : analyse de la chaîne de valeur." },
  { source: 'diagnostic-externe', target: 'swot', type: 'ALIMENTE', description: "Le diagnostic externe alimente la colonne Opportunités / Menaces du SWOT." },
  { source: 'diagnostic-interne', target: 'swot', type: 'ALIMENTE', description: "Le diagnostic interne alimente la colonne Forces / Faiblesses du SWOT." },
  { source: 'pestel', target: 'swot', type: 'ALIMENTE', description: "Le cours propose de restituer le PESTEL directement en opportunités / menaces : le format de sortie du PESTEL est déjà le format d'entrée du SWOT." },
  { source: 'porter-five-forces', target: 'swot', type: 'ALIMENTE', description: "La slide 38 propose un tableau Opportunités / Menaces listant en lignes les 6 forces : c'est le pont explicite Porter → SWOT." },
  { source: 'ressources', target: 'swot', type: 'ALIMENTE', description: "Ressource forte et rare = Force ; ressource manquante ou obsolète = Faiblesse." },
  { source: 'chaine-de-valeur', target: 'swot', type: 'ALIMENTE', description: "Une activité qui différencie devient une force ; une activité qui détruit de la valeur devient une faiblesse." },
  { source: 'swot', target: 'force', type: 'CONTIENT', description: "Case interne positive : ce que l'entreprise possède et qui la sert." },
  { source: 'swot', target: 'faiblesse', type: 'CONTIENT', description: "Case interne négative : ressource ou activité manquante ou défaillante." },
  { source: 'swot', target: 'opportunite', type: 'CONTIENT', description: "Case externe positive : évolution dont l'entreprise peut bénéficier si elle la saisit." },
  { source: 'swot', target: 'menace', type: 'CONTIENT', description: "Case externe négative : évolution susceptible de nuire à l'entreprise." },
  { source: 'force', target: 'opportunite', type: 'NE_PAS_CONFONDRE', description: "La force est EN TOI, l'opportunité est DEHORS. Test infaillible : si l'entreprise disparaissait, cet élément existerait-il encore ? Oui → externe." },
  { source: 'faiblesse', target: 'menace', type: 'NE_PAS_CONFONDRE', description: "Même test que force/opportunité : origine interne contre origine externe." },
  { source: 'swot', target: 'croisements-swot', type: 'PEUT_CONDUIRE_A', description: "Passer de la liste à la réflexion revient à croiser FF × OM pour faire émerger des enjeux stratégiques." },
  { source: 'swot', target: 'saf', type: 'PRECEDE', description: "On croise le SWOT pour produire des options, puis on filtre ces options par le SAF." },
  { source: 'swot', target: 'souhaitabilite', type: 'ALIMENTE', description: "Le SWOT est explicitement l'outil du critère de Souhaitabilité : la stratégie prend-elle en compte les opportunités clés et les menaces ?" },
  { source: 'swot', target: 'porter-five-forces', type: 'NE_PAS_CONFONDRE', description: "Porter mesure l'attractivité structurelle d'un secteur et produit un diagnostic ; le SWOT n'a aucun contenu propre, il compile les résultats des autres outils." },

  // -------------------------------------------------------------------------
  // PESTEL et ses facteurs
  // -------------------------------------------------------------------------
  { source: 'facteur-politique', target: 'pestel', type: 'FAIT_PARTIE_DE', description: "P — processus et actions des organismes gouvernementaux influençant les décisions des entreprises." },
  { source: 'facteur-economique', target: 'pestel', type: 'FAIT_PARTIE_DE', description: "E — fonctionnement de l'économie, inflation, chômage, taux d'intérêt, taux de change." },
  { source: 'facteur-socioculturel', target: 'pestel', type: 'FAIT_PARTIE_DE', description: "S — démographie, éducation, traditions, langue, conditions de vie, religion." },
  { source: 'facteur-technologique', target: 'pestel', type: 'FAIT_PARTIE_DE', description: "T — normes et disponibilité des technologies, hétérogénéité et coûts d'adaptation." },
  { source: 'facteur-environnemental-ethique', target: 'pestel', type: 'FAIT_PARTIE_DE', description: "E — facteur fusionné environnemental et éthique : RSE, pollution, déchets, droits humains, concurrence déloyale." },
  { source: 'facteur-legal', target: 'pestel', type: 'FAIT_PARTIE_DE', description: "L — les lois d'une part, le système répressif d'autre part." },
  { source: 'facteur-politique', target: 'lobbying', type: 'CONTIENT', description: "Deuxième catégorie du facteur politique : les entreprises cherchent à influencer la prise de décision des gouvernements." },
  { source: 'lobbying', target: 'etat-sixieme-force', type: 'ALIMENTE', description: "L'intervention de l'État se fait souvent à la demande des concurrents d'une industrie pour protéger leur marché : c'est le lobbying qui active la 6ᵉ force." },
  { source: 'facteur-environnemental-ethique', target: 'greenwashing', type: 'PEUT_CONDUIRE_A', description: "Le facteur introduit le mécanisme du risque réputationnel amplifié par les médias et réseaux sociaux — exactement celui du greenwashing." },
  { source: 'facteur-environnemental-ethique', target: 'durabilite', type: 'PRECEDE', description: "Cette slide est le pivot entre le chapitre diagnostic et le chapitre durabilité : elle introduit la RSE dans l'analyse externe." },
  { source: 'facteur-socioculturel', target: 'exclusion-indirecte', type: 'PEUT_CONDUIRE_A', description: "Le vieillissement de la population est un facteur socioculturel ; mal traité, il devient une exclusion indirecte." },
  { source: 'facteur-legal', target: 'faisabilite', type: 'ALIMENTE', description: "La troisième question de la faisabilité porte sur les contraintes exogènes, notamment légales." },
  { source: 'pestel', target: 'porter-five-forces', type: 'ALIMENTE', description: "Le PESTEL (macro) explique l'évolution des 5 forces (micro) : une loi augmente les barrières à l'entrée, une taxe rend un substitut compétitif." },
  { source: 'pestel', target: 'porter-five-forces', type: 'NE_PAS_CONFONDRE', description: "PESTEL = le climat général où toutes les entreprises baignent. Porter = la pression des acteurs directs de TON secteur. L'inflation est PESTEL, les rivaux sont Porter." },
  { source: 'pestel', target: 'faisabilite', type: 'ALIMENTE', description: "Le PESTEL est l'outil explicitement associé au critère de Faisabilité du SAF." },
  { source: 'pestel', target: 'diagnostic-interne', type: 'NE_PAS_CONFONDRE', description: "Le PESTEL n'analyse jamais les ressources internes : il ne regarde que ce qui est hors du contrôle de l'entreprise." },

  // -------------------------------------------------------------------------
  // Porter
  // -------------------------------------------------------------------------
  { source: 'pouvoir-clients', target: 'porter-five-forces', type: 'FAIT_PARTIE_DE', description: "Force n°1 : les clients puissants font baisser les prix ou forcent à ajouter de la valeur." },
  { source: 'pouvoir-fournisseurs', target: 'porter-five-forces', type: 'FAIT_PARTIE_DE', description: "Force n°2 : les fournisseurs puissants obtiennent de meilleures conditions ou facturent plus cher." },
  { source: 'menace-substituts', target: 'porter-five-forces', type: 'FAIT_PARTIE_DE', description: "Force n°3 : les substituts forcent les acteurs en place à limiter leurs prix." },
  { source: 'menace-nouveaux-entrants', target: 'porter-five-forces', type: 'FAIT_PARTIE_DE', description: "Force n°4 : la menace agit même si personne n'entre — c'est une pression permanente." },
  { source: 'rivalite-concurrents', target: 'porter-five-forces', type: 'FAIT_PARTIE_DE', description: "Force n°5 : plus la rivalité est intense, moins la rentabilité est forte." },
  { source: 'etat-sixieme-force', target: 'porter-five-forces', type: 'FAIT_PARTIE_DE', description: "6ᵉ force ajoutée par le cours : le pouvoir de régulation, les subventions, l'exception culturelle ou agricole." },
  { source: 'porter-five-forces', target: 'intensite-concurrentielle', type: 'ALIMENTE', description: "L'intensité concurrentielle est la résultante des forces qui s'exercent sur les firmes en place." },
  { source: 'intensite-concurrentielle', target: 'attractivite-industrie', type: 'ALIMENTE', description: "Plus une force est puissante, plus la pression sur les prix ou les coûts est élevée, et moins le secteur est attrayant." },
  { source: 'porter-five-forces', target: 'profit-prix-couts', type: 'UTILISE', description: "Chaque force agit par un canal identifié : elle écrase le prix, gonfle les coûts, ou les deux." },
  { source: 'porter-five-forces', target: 'toile-porter', type: 'UTILISE', description: "La notation 0-5 sur cinq axes visualise le profil des forces : grande toile = secteur peu attractif." },
  { source: 'pouvoir-fournisseurs', target: 'profit-prix-couts', type: 'ILLUSTRE', description: "Seule force qui n'agit que sur les coûts : ton fournisseur te fait payer plus cher, il ne parle pas à tes clients." },
  { source: 'menace-nouveaux-entrants', target: 'barriere-entree', type: 'DEPEND_DE', description: "Les entreprises établies créent des obstacles à l'entrée pour décourager les nouveaux entrants." },
  { source: 'pouvoir-clients', target: 'cout-changement', type: 'DEPEND_DE', description: "Un coût de changement faible augmente le pouvoir du client : « il est facile de changer de marque »." },
  { source: 'pouvoir-clients', target: 'differenciation', type: 'DEPEND_DE', description: "Produit non différencié → client sensible au prix ; caméra très différenciée → client insensible au prix." },
  { source: 'pouvoir-fournisseurs', target: 'concentration', type: 'DEPEND_DE', description: "Peu d'acteurs en amont = beaucoup de pouvoir : « sous la mainmise de Microsoft et d'Intel »." },
  { source: 'menace-substituts', target: 'rapport-prix-rendement', type: 'UTILISE', description: "Pour évaluer la menace d'un substitut, il faut déterminer s'il offre un rapport prix-rendement plus intéressant." },
  { source: 'menace-substituts', target: 'rivalite-concurrents', type: 'NE_PAS_CONFONDRE', description: "Le concurrent fait la même chose que toi ; le substitut satisfait le même besoin autrement. Evian concurrence Vittel ; l'eau du robinet les substitue." },
  { source: 'porter-five-forces', target: 'ocean-rouge', type: 'PEUT_CONDUIRE_A', description: "Forces globalement fortes ⇒ océan rouge. Le corrigé TP02B applique exactement cette séquence." },
  { source: 'porter-five-forces', target: 'ocean-bleu', type: 'PEUT_CONDUIRE_A', description: "Forces faibles ou absentes ⇒ océan bleu. Océan bleu/rouge est la conclusion qualitative de l'analyse de Porter." },
  { source: 'pouvoir-fournisseurs', target: 'systeme-de-valeur', type: 'COMPLETE', description: "Porter regarde le pouvoir du fournisseur ; le système de valeur regarde la chaîne de valeur du fournisseur elle-même." },
  { source: 'porter-five-forces', target: 'bmc', type: 'COMPLETE', description: "Le BMC néglige la concurrence — aucun bloc ne lui est consacré. Il faut donc le compléter par Porter." },

  // -------------------------------------------------------------------------
  // Océan bleu
  // -------------------------------------------------------------------------
  { source: 'ocean-rouge', target: 'ocean-bleu', type: 'S_OPPOSE_A', description: "Rouge : marché existant, concurrence intense, le sang perdu par les entreprises. Bleu : nouvel espace, concurrence minime, aucun navire en vue." },
  { source: 'ocean-bleu', target: 'erac', type: 'UTILISE', description: "La matrice en quatre actions est le moyen concret de sortir de l'océan rouge." },
  { source: 'ocean-bleu', target: 'innovation-valeur', type: 'CONTIENT', description: "Créer simultanément de la valeur pour le client tout en réduisant ses coûts : c'est le test qui distingue l'océan bleu de la simple différenciation." },
  { source: 'erac', target: 'innovation-valeur', type: 'ALIMENTE', description: "Deux actions réduisent les coûts (Exclure, Atténuer), deux augmentent la valeur (Renforcer, Créer) : c'est exactement l'innovation-valeur." },
  { source: 'ocean-bleu', target: 'durabilite', type: 'RENFORCE', description: "« Le concept d'océan bleu est intrinsèquement lié à la durabilité, car il encourage les entreprises à revoir leurs modèles d'affaires pour créer de la valeur à long terme. »" },
  { source: 'ocean-bleu', target: 'eco-conception', type: 'UTILISE', description: "La durabilité (éco-conception, impact social) devient un levier innovation-valeur : elle sert de facteur « Créer » et de facteur « Exclure »." },
  { source: 'ocean-bleu', target: 'barriere-entree', type: 'DEPEND_DE', description: "📚 Un océan bleu rougit : l'avantage n'est durable que si l'entreprise construit des barrières derrière son innovation." },

  // -------------------------------------------------------------------------
  // Ressources et compétences
  // -------------------------------------------------------------------------
  { source: 'ressources-tangibles', target: 'ressources', type: 'FAIT_PARTIE_DE', description: "Actifs aisément identifiables : infrastructures, équipements, usines, brevets, systèmes, circuit de distribution, moyens financiers." },
  { source: 'ressources-intangibles', target: 'ressources', type: 'FAIT_PARTIE_DE', description: "La « richesse cachée » : organisation et management, technologie, image de marque et réputation." },
  { source: 'ressources-tangibles', target: 'ressources-intangibles', type: 'S_OPPOSE_A', description: "Le tangible est facile à identifier et à évaluer, donc facile à acheter et à imiter ; l'intangible non." },
  { source: 'ressources', target: 'transferabilite', type: 'UTILISE', description: "Le critère décisif : plus une ressource est immatérielle et liée aux processus, moins elle peut faire l'objet d'échange ou d'imitation." },
  { source: 'transferabilite', target: 'avantage-concurrentiel-durable', type: 'ALIMENTE', description: "Une usine s'achète ; une réputation construite sur vingt ans, non. C'est ce qui rend l'avantage durable." },
  { source: 'transferabilite', target: 'competence-distinctive', type: 'COMPLETE', description: "⚠️ Le cours utilise la transférabilité/imitabilité à la place du VRIO, absent des supports. C'est cela qu'on attend à l'examen." },
  { source: 'ressources', target: 'competences', type: 'ALIMENTE', description: "Les compétences sont des aptitudes liées à l'utilisation, au déploiement et à l'exploitation des ressources." },
  { source: 'ressources', target: 'competences', type: 'NE_PAS_CONFONDRE', description: "Ressource = ce que l'entreprise POSSÈDE (un stock). Compétence = ce qu'elle SAIT FAIRE avec (un flux)." },
  { source: 'competences', target: 'chaine-de-valeur', type: 'EST_APPLIQUE_DANS', description: "Une compétence s'exerce dans une activité de la chaîne de valeur, où elle génère de la valeur." },
  { source: 'competences', target: 'cybersecurite', type: 'EST_APPLIQUE_DANS', description: "La « communication de crise » est explicitement classée dans les compétences opérationnelles et techniques — utile pour un data breach." },
  { source: 'competences', target: 'autonomie-cognitive', type: 'DEPEND_DE', description: "Une organisation qui délègue systématiquement son analyse à un outil perd une compétence : c'est un risque de diagnostic interne." },

  // -------------------------------------------------------------------------
  // Chaîne de valeur
  // -------------------------------------------------------------------------
  { source: 'activites-principales', target: 'chaine-de-valeur', type: 'FAIT_PARTIE_DE', description: "Les cinq étapes du processus de production et de vente." },
  { source: 'activites-soutien', target: 'chaine-de-valeur', type: 'FAIT_PARTIE_DE', description: "Les quatre fonctions à impact transversal sur toutes les unités." },
  { source: 'logistique-approvisionnement', target: 'activites-principales', type: 'FAIT_PARTIE_DE', description: "Activités logistiques amont : réception, stockage et manutention interne." },
  { source: 'production', target: 'activites-principales', type: 'FAIT_PARTIE_DE', description: "Transformation des matières et sous-ensembles en produits finis." },
  { source: 'logistique-commercialisation', target: 'activites-principales', type: 'FAIT_PARTIE_DE', description: "Activités de livraison des biens et services au client." },
  { source: 'marketing-ventes', target: 'activites-principales', type: 'FAIT_PARTIE_DE', description: "Moyens et méthodes pour faire connaître l'offre, la faire apprécier et déclencher l'achat." },
  { source: 'services', target: 'activites-principales', type: 'FAIT_PARTIE_DE', description: "Activités associées à l'offre principale : formation, maintenance, SAV." },
  { source: 'infrastructure-entreprise', target: 'activites-soutien', type: 'FAIT_PARTIE_DE', description: "Direction générale, comptabilité, juridique, fonctions financières et administratives." },
  { source: 'grh', target: 'activites-soutien', type: 'FAIT_PARTIE_DE', description: "Recrutement, rémunération, motivation, formation, gestion de carrière." },
  { source: 'developpement-technologique', target: 'activites-soutien', type: 'FAIT_PARTIE_DE', description: "Systèmes d'information, R&D, gestion des connaissances." },
  { source: 'approvisionnements', target: 'activites-soutien', type: 'FAIT_PARTIE_DE', description: "Achats de matière, marchandises, fournitures et moyens de production." },
  { source: 'approvisionnements', target: 'logistique-approvisionnement', type: 'NE_PAS_CONFONDRE', description: "L'approvisionnement (soutien) NÉGOCIE et ACQUIERT ; la logistique d'approvisionnement (principale) RÉCEPTIONNE et MANIPULE." },
  { source: 'logistique-approvisionnement', target: 'production', type: 'PRECEDE', description: "L'ordre de la chaîne : ce qui entre est reçu avant d'être transformé." },
  { source: 'production', target: 'logistique-commercialisation', type: 'PRECEDE', description: "Le produit fini est ensuite livré au client." },
  { source: 'logistique-commercialisation', target: 'marketing-ventes', type: 'PRECEDE', description: "Ordre du schéma de Porter, même si le corrigé Smart les traite parfois ensemble." },
  { source: 'marketing-ventes', target: 'services', type: 'PRECEDE', description: "Dernière activité principale : ce qui accompagne le produit après la vente." },
  { source: 'chaine-de-valeur', target: 'marge', type: 'PEUT_CONDUIRE_A', description: "Chaque activité ajoute de la valeur et du coût ; la marge est le solde à l'extrémité de la flèche." },
  { source: 'chaine-de-valeur', target: 'avantage-concurrentiel', type: 'PEUT_CONDUIRE_A', description: "« Leur combinaison peut être à l'origine d'un avantage concurrentiel » — l'avantage naît de l'articulation, pas d'une activité isolée." },
  { source: 'chaine-de-valeur', target: 'facteurs-cles-succes', type: 'ALIMENTE', description: "La détermination des facteurs clés de succès est l'une des quatre applications stratégiques de la chaîne de valeur." },
  { source: 'chaine-de-valeur', target: 'competence-distinctive', type: 'ALIMENTE', description: "L'identification des compétences fondamentales est une application explicite de la chaîne de valeur." },
  { source: 'chaine-de-valeur', target: 'faire-ou-faire-faire', type: 'ALIMENTE', description: "Le choix des activités à externaliser est une application de la chaîne de valeur : on externalise le non stratégique et inefficace." },
  { source: 'chaine-de-valeur', target: 'chaine-valeur-durable', type: 'PEUT_CONDUIRE_A', description: "La version durable allonge le périmètre jusqu'au recyclage et triple les critères : environnemental, social, économique." },
  { source: 'chaine-valeur-durable', target: 'economie-circulaire', type: 'ALIMENTE', description: "En allant jusqu'au recyclage ou à la fin de vie, la chaîne de valeur durable ouvre directement sur l'économie circulaire." },
  { source: 'chaine-valeur-durable', target: 'achats-it-responsables', type: 'UTILISE', description: "Le maillon « approvisionnements » se décline en 7 principes d'achats durables." },
  { source: 'chaine-de-valeur', target: 'systeme-de-valeur', type: 'FAIT_PARTIE_DE', description: "Ton entreprise n'est qu'un maillon : cinq chaînes de valeur emboîtées, des fournisseurs des fournisseurs jusqu'aux clients." },
  { source: 'systeme-de-valeur', target: 'cocreation', type: 'CONTIENT', description: "Première source de création de valeur externe : la forme la plus intense de relation avec un fournisseur." },
  { source: 'systeme-de-valeur', target: 'coopetition', type: 'CONTIENT', description: "Quatrième source : le bien ou service n'aurait pu voir le jour sans la collaboration directe d'un concurrent." },
  { source: 'systeme-de-valeur', target: 'creation-valeur-consommateur', type: 'CONTIENT', description: "Troisième source, la plus subtile : le consommateur final fait partie du processus de création de valeur." },
  { source: 'systeme-de-valeur', target: 'partenaires-cles', type: 'ALIMENTE', description: "« Le bloc des partenaires clés reprend le système de valeur de l'entreprise » — lien explicite Canvas ↔ système de valeur." },
  { source: 'coopetition', target: 'externalite-positive', type: 'PEUT_CONDUIRE_A', description: "Coopérer entre concurrents sur le durable permet de mutualiser des infrastructures vertes et crée des externalités positives." },
  { source: 'creation-valeur-consommateur', target: 'utilisabilite', type: 'ALIMENTE', description: "« Tant que le consommateur final n'utilise pas toutes les fonctions, la valeur du produit est inférieure à 100 % » : c'est le fondement théorique de l'utilisabilité." },
  { source: 'creation-valeur-consommateur', target: 'sobriete-numerique', type: 'RENFORCE', description: "Des fonctionnalités inutilisées consomment des ressources sans créer de valeur." },
  { source: 'externalite-negative', target: 'externalite-positive', type: 'S_OPPOSE_A', description: "L'une impose un coût non intentionnel à des tiers, l'autre accroît leur bien-être." },
  { source: 'externalite-negative', target: 'structure-couts', type: 'EST_APPLIQUE_DANS', description: "On repère une externalité en cherchant quels coûts sociaux/environnementaux N'APPARAISSENT PAS dans la structure de coûts." },

  // -------------------------------------------------------------------------
  // SAF et options
  // -------------------------------------------------------------------------
  { source: 'souhaitabilite', target: 'saf', type: 'FAIT_PARTIE_DE', description: "S — correspondance entre l'environnement et les ressources. Outil : le SWOT." },
  { source: 'acceptabilite', target: 'saf', type: 'FAIT_PARTIE_DE', description: "A — attractivité auprès des parties prenantes, retour et risque acceptables." },
  { source: 'faisabilite', target: 'saf', type: 'FAIT_PARTIE_DE', description: "F — contraintes internes et externes : ressources financières, RH et savoir-faire, contraintes légales." },
  { source: 'souhaitabilite', target: 'acceptabilite', type: 'NE_PAS_CONFONDRE', description: "La souhaitabilité est la pertinence au regard du diagnostic ; l'acceptabilité est l'adhésion des acteurs. Une stratégie peut être pertinente et refusée." },
  { source: 'saf', target: 'options-strategiques', type: 'EST_APPLIQUE_DANS', description: "Le SAF filtre les options formulées après le SWOT ; il prend tout son sens dans la comparaison de 2 ou 3 options." },
  { source: 'options-strategiques', target: 'domination-couts', type: 'CONTIENT', description: "Être le producteur au coût le plus bas — « réduction des coûts par la taille » (corrigé TP02B)." },
  { source: 'options-strategiques', target: 'option-differenciation', type: 'CONTIENT', description: "Offrir une valeur perçue supérieure — « leader mondial en durabilité » (Cours 4, slide 39)." },
  { source: 'options-strategiques', target: 'focalisation', type: 'CONTIENT', description: "Concentrer l'effort sur un segment étroit — « ex : énergie verte »." },
  { source: 'options-strategiques', target: 'innovation-durable', type: 'CONTIENT', description: "Faire de la durabilité le moteur de la création de valeur." },
  { source: 'options-strategiques', target: 'ocean-bleu', type: 'CONTIENT', description: "Créer un espace de marché vierge est la cinquième voie." },
  { source: 'options-strategiques', target: 'proposition-de-valeur', type: 'ALIMENTE', description: "L'option choisie se traduit en promesse au client, puis en architecture et en équation de profit." },
  { source: 'innovation-durable', target: 'eco-conception', type: 'UTILISE', description: "L'innovation durable s'appuie sur l'éco-conception, la circularité et de nouveaux modèles de revenus." },
  { source: 'option-differenciation', target: 'ressources-intangibles', type: 'DEPEND_DE', description: "Une différenciation durable exige des ressources non imitables : savoir-faire, réseau certifié, réputation." },

  // -------------------------------------------------------------------------
  // Business model
  // -------------------------------------------------------------------------
  { source: 'proposition-de-valeur', target: 'business-model', type: 'FAIT_PARTIE_DE', description: "Première composante : ce qu'on promet, à qui." },
  { source: 'architecture-de-valeur', target: 'business-model', type: 'FAIT_PARTIE_DE', description: "Deuxième composante : comment on le produit et le délivre." },
  { source: 'equation-de-profit', target: 'business-model', type: 'FAIT_PARTIE_DE', description: "Troisième composante : ce qu'il en reste." },
  { source: 'business-model', target: 'rcov', type: 'UTILISE', description: "Le RCOV modélise le business model en partant des ressources et compétences, avec une boucle de retour." },
  { source: 'business-model', target: 'bmc', type: 'UTILISE', description: "Le Canvas représente visuellement le business model à partir de la proposition de valeur, en neuf blocs." },
  { source: 'rcov', target: 'bmc', type: 'COMPLETE', description: "Le RCOV montre POURQUOI le modèle tient (logique causale, bouclage) ; le Canvas montre COMMENT il fonctionne bloc par bloc." },
  { source: 'ressources', target: 'rcov', type: 'ALIMENTE', description: "Dans le schéma RCOV, les ressources et compétences sont au sommet : tout part d'elles." },
  { source: 'architecture-de-valeur', target: 'chaine-de-valeur', type: 'UTILISE', description: "« Il s'agit principalement de la chaîne de valeur et du système de valeur. »" },
  { source: 'architecture-de-valeur', target: 'faire-ou-faire-faire', type: 'CONTIENT', description: "Première décision stratégique de l'architecture de valeur." },
  { source: 'architecture-de-valeur', target: 'couts-fixes-variables', type: 'CONTIENT', description: "Seconde décision : gérer la dualité coûts fixes / coûts variables." },
  { source: 'proposition-de-valeur', target: 'flux-revenus', type: 'ALIMENTE', description: "« La proposition de valeur est la source des flux de revenus que l'entreprise est en mesure de dégager. »" },
  { source: 'architecture-de-valeur', target: 'structure-couts', type: 'ALIMENTE', description: "L'organisation de la chaîne de valeur produit le volume et la structure des charges." },
  { source: 'flux-revenus', target: 'equation-de-profit', type: 'ALIMENTE', description: "Branche gauche du RCOV : l'offre produit les revenus." },
  { source: 'structure-couts', target: 'equation-de-profit', type: 'ALIMENTE', description: "Branche droite du RCOV : l'organisation produit les charges." },
  { source: 'equation-de-profit', target: 'profit-prix-couts', type: 'NE_PAS_CONFONDRE', description: "Porter raisonne à l'unité (Prix − Coûts) pour montrer la pression des forces ; le RCOV raisonne en agrégats (volume et structure) pour décrire l'architecture économique." },
  { source: 'segments-clients', target: 'bmc', type: 'FAIT_PARTIE_DE', description: "Bloc 1 : les groupes d'individus ou d'organisations que cible l'entreprise." },
  { source: 'proposition-de-valeur', target: 'bmc', type: 'FAIT_PARTIE_DE', description: "Bloc central : la charnière entre le monde du client et le monde de la production." },
  { source: 'canaux', target: 'bmc', type: 'FAIT_PARTIE_DE', description: "Bloc 3 : les modalités par lesquelles l'entreprise entre en contact avec ses segments." },
  { source: 'relations-clients', target: 'bmc', type: 'FAIT_PARTIE_DE', description: "Bloc 4 : acquérir, fidéliser, développer les ventes." },
  { source: 'flux-revenus', target: 'bmc', type: 'FAIT_PARTIE_DE', description: "Bloc 5 : « Que sont-ils prêts à payer ? Comment payent-ils ? »" },
  { source: 'ressources-cles', target: 'bmc', type: 'FAIT_PARTIE_DE', description: "Bloc 6 : les actifs les plus importants requis pour réaliser la proposition de valeur." },
  { source: 'activites-cles', target: 'bmc', type: 'FAIT_PARTIE_DE', description: "Bloc 7 : les choses les plus importantes à faire pour que le modèle fonctionne." },
  { source: 'partenaires-cles', target: 'bmc', type: 'FAIT_PARTIE_DE', description: "Bloc 8 : le réseau de fournisseurs et partenaires grâce auquel le modèle fonctionne." },
  { source: 'structure-couts', target: 'bmc', type: 'FAIT_PARTIE_DE', description: "Bloc 9 : la structure, le niveau et les flux de coûts induits par les trois blocs précédents." },
  { source: 'ressources-cles', target: 'ressources', type: 'EST_EXEMPLE_DE', description: "Le BMC propose une typologie plus courte (physiques, intellectuelles, humaines, financières) que les six natures du diagnostic interne." },
  { source: 'bmc', target: 'bmc-durable', type: 'PRECEDE', description: "Le BMC durable ajoute les trois blocs manquants : mission (0), impacts positifs (10), externalités négatives (11)." },
  { source: 'mission', target: 'bmc-durable', type: 'FAIT_PARTIE_DE', description: "Bloc (0) : la numérotation à zéro signifie que la mission précède et conditionne tous les autres blocs." },
  { source: 'impacts-positifs', target: 'bmc-durable', type: 'FAIT_PARTIE_DE', description: "Bloc (10) : effets bénéfiques pour la société, l'environnement et les clients." },
  { source: 'externalite-negative', target: 'bmc-durable', type: 'FAIT_PARTIE_DE', description: "Bloc (11) : les effets indésirables ou dommages causés par l'activité." },
  { source: 'bmc-durable', target: 'metamorphose-bmc', type: 'UTILISE', description: "La table de transformation applique la question de durabilité aux neuf variables du modèle traditionnel." },
  { source: 'metamorphose-bmc', target: 'economie-fonctionnalite', type: 'PEUT_CONDUIRE_A', description: "Le bloc « sources de revenus » se transforme en leasing, services, remise à neuf : on vend l'usage plutôt que le bien." },
  { source: 'metamorphose-bmc', target: 'tensions-strategiques', type: 'ILLUSTRE', description: "La ligne « structure de coûts » contient la réponse à la tension CT/LT : investissement initial élevé, bénéfices à long terme, réinvestissement des économies en R&D." },
  { source: 'economie-fonctionnalite', target: 'economie-circulaire', type: 'RENFORCE', description: "En gardant la propriété du bien, l'entreprise internalise l'intérêt à le faire durer et à le récupérer." },
  { source: 'bmc-durable', target: 'odd', type: 'UTILISE', description: "Les ODD fournissent la grille sur laquelle situer les impacts positifs et les externalités négatives." },
  { source: 'greenwashing', target: 'externalite-negative', type: 'DEPEND_DE', description: "Un BM « durable » de façade est du greenwashing si les externalités négatives restent cachées dans les coûts." },
  { source: 'greenwashing', target: 'labels-environnementaux', type: 'S_OPPOSE_A', description: "Les labels indépendants et les preuves chiffrées sont l'antidote au greenwashing." },
  { source: 'bmc', target: 'porter-five-forces', type: 'NE_PAS_CONFONDRE', description: "Le Canvas décrit le fonctionnement interne et néglige la concurrence ; Porter mesure la pression concurrentielle et ignore l'architecture interne." },

  // -------------------------------------------------------------------------
  // Durabilité
  // -------------------------------------------------------------------------
  { source: 'durabilite', target: 'durabilite-forte', type: 'CONTIENT', description: "La position défendue par le cours : le capital naturel n'est pas substituable." },
  { source: 'durabilite-forte', target: 'durabilite-faible', type: 'S_OPPOSE_A', description: "Forte : capital naturel non substituable. Faible : substitution admise par le capital technique ou économique." },
  { source: 'durabilite-forte', target: 'sobriete-numerique', type: 'ALIMENTE', description: "Si le capital naturel est non substituable, l'efficacité et la compensation ne suffisent pas : il faut réduire en valeur absolue." },
  { source: 'durabilite-forte', target: 'capital-naturel', type: 'UTILISE', description: "La définition repose sur la distinction entre capital naturel, social et économique." },
  { source: 'durabilite', target: 'donut', type: 'ILLUSTRE', description: "La définition contient déjà le plancher social (besoins de tous) et le plafond écologique (limites planétaires)." },
  { source: 'durabilite', target: 'developpement-durable', type: 'NE_PAS_CONFONDRE', description: "Le cours définit la durabilité (Agenda 2030) mais emploie « développement durable » sans le définir séparément ; la bibliographie contient des références critiques de cette seconde notion." },
  { source: 'developpement-durable', target: 'transition-ecologique', type: 'NE_PAS_CONFONDRE', description: "Bourg (2012) intitule son article « Transition écologique, plutôt que développement durable » : le titre est déjà une critique." },
  { source: 'agenda-2030', target: 'odd', type: 'CONTIENT', description: "Les 17 ODD et leurs 169 cibles forment la clé de voûte de l'Agenda 2030." },
  { source: 'agenda-2030', target: 'cinq-p', type: 'UTILISE', description: "Les ODD s'articulent autour des 5P : Populations, Planète, Prospérité, Paix et Partenariats." },
  { source: 'odd', target: 'odd-12', type: 'CONTIENT', description: "L'ODD 12 est le seul détaillé par le cours, et le plus mobilisable : consommation et production responsables." },
  { source: 'odd-12', target: 'trois-r', type: 'ALIMENTE', description: "La cible énonce « la prévention, la réduction, le recyclage et la réutilisation » : la prévention et la réduction viennent avant le recyclage." },
  { source: 'odd-12', target: 'achats-it-responsables', type: 'ALIMENTE', description: "« Acheter moins (avant l'appel d'offres) // ODD » : le cours relie explicitement l'ODD 12 aux achats." },
  { source: 'agenda-2030', target: 'sdd-2030', type: 'PEUT_CONDUIRE_A', description: "La Stratégie pour le développement durable 2030 est la déclinaison suisse de l'Agenda 2030." },
  { source: 'sdd-2030', target: 'monet-2030', type: 'UTILISE', description: "Le système d'indicateurs MONET 2030 de l'OFS mesure l'avancement de la Suisse vers les ODD." },
  { source: 'odd', target: 'wedding-cake', type: 'EST_APPLIQUE_DANS', description: "Le Wedding Cake répartit les 17 ODD sur trois étages : biosphère, société, économie." },
  { source: 'trois-cercles-elkington', target: 'mickey-mouse-model', type: 'PRECEDE', description: "Le Mickey Mouse Model est la caricature critique des trois cercles : en pratique l'économique domine." },
  { source: 'mickey-mouse-model', target: 'wedding-cake', type: 'PRECEDE', description: "Après la critique vient la correction : hiérarchie imbriquée, la biosphère conditionne tout." },
  { source: 'trois-cercles-elkington', target: 'durabilite-faible', type: 'ILLUSTRE', description: "Trois cercles de taille égale sur le même plan suggèrent un arbitrage possible entre eux : c'est une représentation de durabilité faible." },
  { source: 'wedding-cake', target: 'durabilite-forte', type: 'ILLUSTRE', description: "Les trois cercles suggèrent un équilibre donc un arbitrage ; le Wedding Cake pose une dépendance donc une condition non négociable." },
  { source: 'limites-planetaires', target: 'plafond-ecologique', type: 'ALIMENTE', description: "Les 9 limites planétaires constituent le bord extérieur du Donut." },
  { source: 'plancher-social', target: 'donut', type: 'FAIT_PARTIE_DE', description: "Bord intérieur : 12 objectifs pour une vie digne, appuyés sur la Déclaration universelle des droits de l'homme." },
  { source: 'plafond-ecologique', target: 'donut', type: 'FAIT_PARTIE_DE', description: "Bord extérieur : les limites planétaires au-delà desquelles des basculements irréversibles peuvent se produire." },
  { source: 'donut', target: 'durabilite-forte', type: 'ILLUSTRE', description: "L'espace sûr et juste n'est pas négociable : on ne compense pas un dépassement par un abaissement." },
  { source: 'donut', target: 'exclusion-indirecte', type: 'PEUT_CONDUIRE_A', description: "Réduire ses impacts en excluant des publics échange un dépassement écologique contre un abaissement social : ce n'est pas de la durabilité." },
  { source: 'empreinte-ecologique', target: 'jour-depassement', type: 'ALIMENTE', description: "Le jour du dépassement est estimé en croisant l'empreinte écologique et la biocapacité." },
  { source: 'biocapacite', target: 'jour-depassement', type: 'ALIMENTE', description: "Seconde grandeur du calcul : la capacité des écosystèmes à se régénérer et à absorber les déchets." },
  { source: 'iso-durabilite', target: 'labels-environnementaux', type: 'COMPLETE', description: "Les normes ISO structurent les trois types de déclarations environnementales sur lesquelles reposent les labels." },
  { source: 'certifications-durabilite', target: 'greenwashing', type: 'S_OPPOSE_A', description: "Une certification par un tiers est une preuve ; sans preuve, l'affichage devient du greenwashing." },
  { source: 'resilience', target: 'souverainete-numerique', type: 'EST_APPLIQUE_DANS', description: "L'exercice du cours applique la résilience au système informatique face à une coupure de service américaine ou une rupture d'approvisionnement asiatique." },

  // -------------------------------------------------------------------------
  // Circularité et achats
  // -------------------------------------------------------------------------
  { source: 'economie-lineaire', target: 'economie-circulaire', type: 'S_OPPOSE_A', description: "La linéaire se termine par « incinération et mise en décharge » : le produit devient un déchet définitif. La circularité supprime cette fin." },
  { source: 'trois-r', target: 'economie-circulaire', type: 'FAIT_PARTIE_DE', description: "La hiérarchie Réduire > Réutiliser > Recycler est le principe d'action de l'économie circulaire." },
  { source: 'eco-conception', target: 'economie-circulaire', type: 'ALIMENTE', description: "L'écoconception n'est pas une boucle : elle agit à la source pour rendre toutes les boucles possibles." },
  { source: 'eco-conception', target: 'cycle-de-vie', type: 'UTILISE', description: "Concevoir en minimisant l'impact sur tout le cycle de vie : matières, production, usage, fin de vie." },
  { source: 'reconditionnement', target: 'trois-r', type: 'FAIT_PARTIE_DE', description: "Le reconditionnement relève du deuxième R : réutiliser, avec vérification, nettoyage des composants ET des données, et réparations." },
  { source: 'reconditionnement', target: 'protection-donnees', type: 'DEPEND_DE', description: "L'exigence de nettoyage des données fait du reconditionnement le pont entre circularité et protection des données." },
  { source: 'trois-r', target: 'deee', type: 'S_OPPOSE_A', description: "Les 3R visent précisément à minimiser le besoin de nouveaux appareils et les déchets électroniques." },
  { source: 'obsolescence', target: 'deee', type: 'PEUT_CONDUIRE_A', description: "L'obsolescence rapide des terminaux aggrave le volume des déchets électroniques." },
  { source: 'achats-it-responsables', target: 'sept-principes-achats', type: 'UTILISE', description: "Sept critères applicables à toute décision d'achat, du prix à l'élimination." },
  { source: 'sept-principes-achats', target: 'cout-cycle-de-vie', type: 'CONTIENT', description: "Principe n°2, le plus stratégique : il déplace la décision du prix affiché vers le coût complet." },
  { source: 'sept-principes-achats', target: 'labels-environnementaux', type: 'CONTIENT', description: "Principe n°3 : sans preuve, un critère d'achat reste déclaratif." },
  { source: 'achats-it-responsables', target: 'pap-swiss', type: 'UTILISE', description: "La boîte à outils suisse officielle : matrice des pertinences, coûts du cycle de vie, bases juridiques, toolbox." },
  { source: 'achats-it-responsables', target: 'electronics-watch', type: 'UTILISE', description: "Réponse non technologique à la traçabilité éthique : le monitoring indépendant par la société civile des régions de production." },
  { source: 'achats-it-responsables', target: 'approvisionnements', type: 'EST_APPLIQUE_DANS', description: "Les achats responsables sont la déclinaison durable de l'activité de soutien « approvisionnements »." },
  { source: 'cout-cycle-de-vie', target: 'structure-couts', type: 'ALIMENTE', description: "Raisonner en coût complet change la structure de coûts affichée : un équipement bon marché mais énergivore coûte plus cher." },
  { source: 'trois-r', target: 'sobriete-numerique', type: 'COMPLETE', description: "Même structure logique : Réduire / Questionner, Réutiliser / Transférer, Recycler / Améliorer. Agir sur le besoin avant la technique." },
  { source: 'achats-it-responsables', target: 'sobriete-numerique', type: 'COMPLETE', description: "Acheter moins / Acheter mieux / Utiliser mieux reproduit exactement Questionner / Transférer / Améliorer." },

  // -------------------------------------------------------------------------
  // Numérique et sobriété
  // -------------------------------------------------------------------------
  { source: 'transformation-numerique', target: 'durabilite', type: 'RENFORCE', description: "Dématérialisation, optimisation des ressources, mesure d'impact, traçabilité, économie de la fonctionnalité." },
  { source: 'transformation-numerique', target: 'effet-rebond', type: 'PEUT_CONDUIRE_A', description: "Le numérique a un coût écologique propre et ses gains d'efficacité peuvent être réabsorbés par la croissance des usages." },
  { source: 'transformation-numerique', target: 'trois-postes-numerique', type: 'DEPEND_DE', description: "Le numérique n'est pas immatériel : il repose sur des terminaux, des data centers et des réseaux." },
  { source: 'data-center', target: 'trois-postes-numerique', type: 'FAIT_PARTIE_DE', description: "46 % de l'impact en France, avec une croissance tirée par l'IA." },
  { source: 'trois-postes-numerique', target: 'achats-it-responsables', type: 'ALIMENTE', description: "La moitié de l'impact vient des terminaux, donc de leur fabrication et de leur renouvellement : c'est ce qui justifie les achats IT responsables." },
  { source: 'effet-rebond', target: 'sobriete-numerique', type: 'ALIMENTE', description: "La lucidité — penser les conséquences directes et indirectes — consiste précisément à anticiper l'effet rebond." },
  { source: 'effet-rebond', target: 'effet-offre-usage', type: 'COMPLETE', description: "Deux grilles pour décomposer l'impact : par source (offre / usage) et par mécanisme de réabsorption." },
  { source: 'boucle-retroaction', target: 'effet-rebond', type: 'RENFORCE', description: "Plus d'infrastructures → plus de services → plus d'usages → plus de besoins ressentis → plus d'infrastructures : une boucle qui s'auto-amplifie." },
  { source: 'boucle-retroaction', target: 'pensee-systemique', type: 'ILLUSTRE', description: "« Rétroaction positive » ne veut pas dire bénéfique : c'est une boucle qui s'auto-amplifie, donc explosive et non régulée." },
  { source: 'sobriete-numerique', target: 'besoins-fondamentaux', type: 'DEPEND_DE', description: "Questionner les besoins en première intention suppose de savoir distinguer le besoin (stable, universel) du satisfier (variable, extensible)." },
  { source: 'sobriete-numerique', target: 'sobriete-injuste', type: 'NE_PAS_CONFONDRE', description: "Le critère central n'est pas « moins » mais moins de superflu, sans réduire l'essentiel. Supprimer des aides à la compréhension serait une sobriété injuste." },
  { source: 'sobriete-injuste', target: 'plancher-social', type: 'S_OPPOSE_A', description: "Une sobriété qui supprime ce qui rend le service accessible fait tomber sous le plancher social." },
  { source: 'sobriete-numerique', target: 'rgesn', type: 'UTILISE', description: "Le référentiel donne les six leviers concrets : architecture, contenus, flux, hébergement, composants, durée de vie des données." },
  { source: 'sobriete-numerique', target: 'data-center', type: 'EST_APPLIQUE_DANS', description: "Les leviers techniques (consolidation, virtualisation, refroidissement) ne suffisent pas sans une démarche de sobriété qui neutralise l'effet rebond." },
  { source: 'effets-ocde', target: 'effet-rebond', type: 'CONTIENT', description: "Les effets systémiques incluent les effets rebond, qui rendent le bilan net complexe à établir." },
  { source: 'effets-ocde', target: 'transformation-numerique', type: 'EST_APPLIQUE_DANS', description: "Structure de réponse la plus rigoureuse : effet direct, effet facilitateur, effet systémique, bilan net." },
  { source: 'quatre-criteres-donut', target: 'donut', type: 'EST_APPLIQUE_DANS', description: "Grille d'évaluation d'un service numérique : besoin social réel, accessibilité, impacts sur le cycle de vie, absence de hausse artificielle des usages." },
  { source: 'quatre-criteres-donut', target: 'accessibilite-numerique', type: 'DEPEND_DE', description: "Le critère n°2 — rester accessible — est celui sur lequel SilverDigital échoue." },
  { source: 'economie-attention', target: 'dark-patterns', type: 'UTILISE', description: "Les dark patterns et l'exploitation du système dopaminergique sont les outils de la captation d'attention." },
  { source: 'economie-attention', target: 'technofeodalisme', type: 'RENFORCE', description: "La captation de l'attention et de la valeur par quelques plateformes produit une domination de type féodal." },
  { source: 'economie-attention', target: 'sobriete-numerique', type: 'S_OPPOSE_A', description: "Un modèle d'affaires fondé sur l'augmentation du temps passé est en tension directe avec le questionnement du besoin." },
  { source: 'dark-patterns', target: 'opt-in', type: 'S_OPPOSE_A', description: "Une case pré-cochée ou un parcours culpabilisant vide de sens le consentement libre et éclairé." },
  { source: 'cyber-power', target: 'souverainete-numerique', type: 'ALIMENTE', description: "La redistribution de la puissance vers des acteurs privés propriétaires des infrastructures pose la question de la souveraineté." },
  { source: 'souverainete-numerique', target: 'pouvoir-fournisseurs', type: 'ILLUSTRE', description: "La dépendance aux hyperscalers américains et la criticité des terres rares sont un cas d'école de pouvoir de négociation des fournisseurs." },
  { source: 'debat-numerique-durabilite', target: 'business-model', type: 'DEPEND_DE', description: "« La difficulté centrale ne vient pas d'abord de la technique, mais du modèle économique » : on ne résoudra pas la sobriété par la technique, il faut changer l'équation de profit." },
  { source: 'debat-numerique-durabilite', target: 'tensions-strategiques', type: 'ILLUSTRE', description: "Ni techno-solutionnisme, ni réduction indistincte : la position solide est un arbitrage sur l'utilité sociale des services." },
  { source: 'besoins-fondamentaux', target: 'utilisabilite', type: 'ALIMENTE', description: "Nussbaum : avoir une application n'est pas avoir la capabilité de l'utiliser." },
  { source: 'oris', target: 'sobriete-numerique', type: 'ILLUSTRE', description: "Rendre visible un impact abstrait est une dimension comportementale de la sobriété." },

  // -------------------------------------------------------------------------
  // RNE
  // -------------------------------------------------------------------------
  { source: 'rne', target: 'quatre-axes-rne', type: 'CONTIENT', description: "Données, social, environnement, éthique et gouvernance — quatre domaines constants sous des étiquettes variables." },
  { source: 'rne', target: 'charte-numerique', type: 'UTILISE', description: "La charte est l'outil opérationnel de la RNE : identifier, impliquer, formaliser, diffuser, faire vivre." },
  { source: 'rne', target: 'gouvernance-numerique-roles', type: 'UTILISE', description: "DPO, CDO, CISO, Chief AI Officer, Green Officer, Accessibility Officer : qui pilote quoi." },
  { source: 'rne', target: 'accessibilite-numerique', type: 'CONTIENT', description: "L'accessibilité est l'axe social de la RNE, et son terrain d'application le plus concret." },
  { source: 'rne', target: 'sobriete-numerique', type: 'CONTIENT', description: "L'axe environnement de la RNE : sobriété, durée de vie du matériel, achats responsables, écoconception." },
  { source: 'rne', target: 'protection-donnees', type: 'CONTIENT', description: "L'axe données : protection, cybersécurité, transparence." },
  { source: 'rne', target: 'ia', type: 'CONTIENT', description: "L'axe éthique et gouvernance : usage responsable de l'IA, transparence algorithmique." },
  { source: 'rne', target: 'avantage-concurrentiel-durable', type: 'PEUT_CONDUIRE_A', description: "Confiance, image, réduction des risques légaux et cyber, innovation, différenciation." },
  { source: 'charte-numerique', target: 'charte-inr', type: 'EST_EXEMPLE_DE', description: "Les 5 engagements de l'Institut du Numérique Responsable sont un modèle de charte." },
  { source: 'charte-inr', target: 'trois-u', type: 'CONTIENT', description: "Les services numériques doivent être Utiles, Utilisables, Utilisés." },
  { source: 'trois-u', target: 'sobriete-numerique', type: 'UTILISE', description: "Le premier U — Utile — est la question de la sobriété : ce service répond-il à un besoin réel ?" },
  { source: 'trois-u', target: 'utilisabilite', type: 'UTILISE', description: "Le deuxième U — Utilisable — est la question de l'accessibilité et de l'utilisabilité." },
  { source: 'trois-u', target: 'creation-valeur-consommateur', type: 'UTILISE', description: "Le troisième U — Utilisé — est la création de valeur par le consommateur final." },
  { source: 'cinq-principes-collecte', target: 'protection-donnees', type: 'FAIT_PARTIE_DE', description: "But indiqué, transparence, minimisation, compréhension, données correctes — ils recoupent les principes LPD/RGPD." },
  { source: 'cinq-principes-collecte', target: 'minimisation-donnees', type: 'CONTIENT', description: "Principe n°3 : ne collecter que le strictement nécessaire à la finalité." },
  { source: 'cinq-principes-collecte', target: 'accessibilite-numerique', type: 'DEPEND_DE', description: "Principe n°4 « compréhension de la collecte » : une politique de confidentialité illisible ne le satisfait pas." },
  { source: 'privacy-by-design', target: 'privacy-by-default', type: 'NE_PAS_CONFONDRE', description: "By design = protection intégrée dès la conception. By default = réglages les plus protecteurs activés d'origine." },
  { source: 'privacy-by-design', target: 'accessibilite-numerique', type: 'COMPLETE', description: "Parallèle méthodologique : dans les deux cas, corriger après coup coûte beaucoup plus cher et donne un résultat inférieur." },
  { source: 'privacy-by-default', target: 'opt-in', type: 'UTILISE', description: "Le consentement actif — case non cochée par défaut — est l'application concrète du principe." },
  { source: 'protection-donnees', target: 'pets', type: 'UTILISE', description: "Chiffrement, anonymisation, pseudonymisation, calcul sécurisé." },
  { source: 'protection-donnees', target: 'integrite-numerique', type: 'COMPLETE', description: "L'art. 21A Cst-GE ajoute au socle LPD/RGPD le droit à une vie hors ligne, le droit à l'oubli et l'inclusion numérique." },
  { source: 'minimisation-donnees', target: 'sobriete-numerique', type: 'RENFORCE', description: "Moins de données collectées = moins de stockage, moins d'énergie, moins de surface de risque cyber." },
  { source: 'gouvernance-donnees', target: 'rgesn', type: 'UTILISE', description: "La durée de vie des données figure parmi les six leviers d'écoconception : conserver l'inutile coûte de l'énergie." },
  { source: 'cybersecurite', target: 'protection-donnees', type: 'RENFORCE', description: "Plan de gestion de crise, notification en cas de data breach : la sécurité est la condition pratique de la protection." },
  { source: 'ia', target: 'ai-act', type: 'DEPEND_DE', description: "Le règlement européen classe les usages en quatre niveaux de risque et impose des obligations échelonnées." },
  { source: 'ia', target: 'enjeux-ethiques-ia', type: 'CONTIENT', description: "Biais, explicabilité, responsabilité, données, environnement, autonomie cognitive, souveraineté." },
  { source: 'ai-act', target: 'position-suisse-ia', type: 'NE_PAS_CONFONDRE', description: "L'UE régule ex ante par les risques ; la Suisse adapte le droit existant sans loi générale. Mais une entreprise suisse opérant en Europe reste soumise à l'AI Act." },
  { source: 'ai-act', target: 'facteur-legal', type: 'EST_EXEMPLE_DE', description: "Excellent cas d'application du facteur légal du PESTEL : une réglementation étrangère contraint une entreprise suisse." },
  { source: 'ia', target: 'data-center', type: 'DEPEND_DE', description: "La demande d'électricité des data centers liée à l'IA croît d'environ 16 %/an, soit un doublement tous les quatre ans." },
  { source: 'enjeux-ethiques-ia', target: 'autonomie-cognitive', type: 'CONTIENT', description: "La délégation systématique au LLM appauvrit la capacité de réflexion de l'organisation." },

  // -------------------------------------------------------------------------
  // Accessibilité
  // -------------------------------------------------------------------------
  { source: 'accessibilite-numerique', target: 'double-levier-accessibilite', type: 'CONTIENT', description: "Levier de responsabilité numérique ET levier de création de valeur durable." },
  { source: 'double-levier-accessibilite', target: 'avantage-concurrentiel-durable', type: 'PEUT_CONDUIRE_A', description: "Élargissement du marché adressable, différenciation et confiance : l'accessibilité cesse d'être un coût." },
  { source: 'accessibilite-numerique', target: 'wcag', type: 'UTILISE', description: "Le standard international, décliné en quatre principes et trois niveaux de conformité." },
  { source: 'pour', target: 'wcag', type: 'FAIT_PARTIE_DE', description: "Perceptible, Opérable/Utilisable, Compréhensible, Robuste : les quatre principes fondateurs." },
  { source: 'accessibilite-numerique', target: 'european-accessibility-act', type: 'DEPEND_DE', description: "Entré en application en juin 2025, il vise explicitement les banques et services financiers." },
  { source: 'accessibilite-numerique', target: 'lhand', type: 'DEPEND_DE', description: "La révision étend le champ d'application aux prestations proposées par des privés." },
  { source: 'accessibilite-numerique', target: 'cadre-legal-accessibilite', type: 'DEPEND_DE', description: "eCH-0059, EN 301 549, ADA, Unruh Civil Rights Act, RGAA : l'empilement des textes." },
  { source: 'lhand', target: 'exclusion-indirecte', type: 'CONTIENT', description: "La révision vise explicitement la discrimination indirecte, pas seulement la discrimination directe." },
  { source: 'exclusion-indirecte', target: 'discrimination-directe', type: 'NE_PAS_CONFONDRE', description: "La directe est explicitement fondée sur le handicap ; l'indirecte résulte d'une règle apparemment neutre." },
  { source: 'exclusion-indirecte', target: 'externalite-negative', type: 'EST_EXEMPLE_DE', description: "Un coût non intentionnel imposé à d'autres : la charge est reportée sur les clients, leurs proches et les associations." },
  { source: 'accessibilite-numerique', target: 'inclusion-numerique', type: 'ALIMENTE', description: "Comprendre, naviguer, interagir, bénéficier : le quatrième verbe est décisif." },
  { source: 'accessibilite-numerique', target: 'utilisabilite', type: 'NE_PAS_CONFONDRE', description: "Un service peut être accessible (conforme AA) et inutilisable (parcours en 12 étapes, vocabulaire technique)." },
  { source: 'inclusion-numerique', target: 'illectronisme', type: 'S_OPPOSE_A', description: "L'illectronisme n'est pas un handicap mais un manque de compétences ou d'équipement — l'effet d'exclusion est identique." },
  { source: 'accessibilite-numerique', target: 'kpi-accessibilite', type: 'UTILISE', description: "Distinguer KPI de moyen (conformité WCAG) et KPI de résultat (taux de réussite des parcours par de vrais utilisateurs)." },
  { source: 'accessibilite-numerique', target: 'integrite-numerique', type: 'DEPEND_DE', description: "L'art. 21A al. 2 consacre le droit à une vie hors ligne ; l'al. 4 engage l'État à favoriser l'inclusion numérique." },
  { source: 'integrite-numerique', target: 'exclusion-indirecte', type: 'S_OPPOSE_A', description: "Le « droit à une vie hors ligne » est l'argument juridique le plus fort contre une stratégie « Digital First » exclusive." },
  { source: 'kpi-accessibilite', target: 'kpi', type: 'EST_EXEMPLE_DE', description: "Application concrète de la distinction générale entre indicateurs de moyen et de résultat." },

  // -------------------------------------------------------------------------
  // Méthode et pilotage
  // -------------------------------------------------------------------------
  { source: 'collecte-donnees-utilisateurs', target: 'observation', type: 'CONTIENT', description: "Méthode qualitative : capte ce que les gens font, pas ce qu'ils disent." },
  { source: 'collecte-donnees-utilisateurs', target: 'interview', type: 'CONTIENT', description: "Méthode qualitative : accède aux motivations et aux émotions." },
  { source: 'collecte-donnees-utilisateurs', target: 'sondage', type: 'CONTIENT', description: "Méthode quantitative : mesure et généralise." },
  { source: 'collecte-donnees-utilisateurs', target: 'focus-group', type: 'CONTIENT', description: "Méthode qualitative de groupe : fait émerger et confronter des idées." },
  { source: 'observation', target: 'besoin-latent', type: 'ALIMENTE', description: "Le besoin latent se découvre par l'observation et les « 5 pourquoi », pas en le demandant." },
  { source: 'observation', target: 'sondage', type: 'NE_PAS_CONFONDRE', description: "Observation = qualitatif, usage réel, sans interaction. Sondage = quantitatif, questions fermées, déclaratif." },
  { source: 'collecte-donnees-utilisateurs', target: 'segments-clients', type: 'ALIMENTE', description: "Comprendre l'utilisateur fonde le segment et la proposition de valeur." },
  { source: 'collecte-donnees-utilisateurs', target: 'exclusion-indirecte', type: 'S_OPPOSE_A', description: "Observer puis interviewer les seniors avant le virage « Digital First » aurait révélé les blocages et évité l'exclusion." },
  { source: 'collecte-donnees-utilisateurs', target: 'parties-prenantes', type: 'ALIMENTE', description: "La collecte alimente l'analyse des parties prenantes en données réelles plutôt qu'en suppositions." },
  { source: 'lisaec', target: 'dei', type: 'CONTIENT', description: "L'étape A — Argumenter — se rédige en D-E-I : définir, expliquer, illustrer." },
  { source: 'lisaec', target: 'verbes-consigne', type: 'UTILISE', description: "L'étape L — Lire — consiste à décoder le verbe de consigne, qui commande la forme de la réponse." },
  { source: 'lisaec', target: 'tensions-strategiques', type: 'UTILISE', description: "L'étape C — Conclure — exige de trancher et de nommer la tension." },
  { source: 'lisaec', target: 'pensee-systemique', type: 'UTILISE', description: "L'étape E — Étendre — fait les liens transversaux : c'est ce qui signale la maîtrise." },
  { source: 'kpi', target: 'controle', type: 'ALIMENTE', description: "Les indicateurs sont le matériau du système de contrôle et des reportings réguliers." },
  { source: 'idg', target: 'odd', type: 'RENFORCE', description: "Les ODD décrivent ce qu'il faut atteindre ; les IDG décrivent les capacités humaines nécessaires pour y parvenir." },
  { source: 'tensions-strategiques', target: 'saf', type: 'UTILISE', description: "Le critère de décision d'un arbitrage est souvent le SAF, les parties prenantes ou l'horizon temporel." },
]
